#pragma once

enum class EMailSetType{
  None = 0,
  CHAT = 1,
  BATTLE = 3,
  ACT = 4,
  NOTICE = 5,
  SYS = 6,
  COMMUNITY_CENTER = 15,
  MONSTER_REPORT = 7,
  RESOURCE_GATHER_REPORT = 8,
  ROMAN_SOUL_REPORT = 9,
  PYRAMID_BATTLE_REPORT = 10,
  RUINS_BATTLE_REPORT = 12,
  DEVILVALLEY_BATTLE_REPORT = 13,
  BOSS_REPORT = 14,
  INFO_MAIL = 19,
  ALLIANCE = 2,
  SCOUT_REPORT = 11,
  NEW_BATTLE = 18,
  NEW_SYS = 17,
  COLLECT = 16
};