#pragma once 
#include "Include/IncludeEngine.h"
#include "Module/Building/BuildingTips/BuildingTips.Enum.h"

class UIBuildingTipButton;
class BuildingTipsHandle{
  void ButtonInfoCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonUpgradeCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonStarUpgradeCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonTrainCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonTradeCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonAuctionCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonResearchCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonBuildTrapCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonHelpCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonReinforcementsCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonWishCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonETreasureCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonAllianceBattleCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonDefendCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonMilitaryInfoCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonCityInfoCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonCityBuffCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonHealCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonCollectCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonForgingCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonStorageBoxCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonBoostCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonBoostByToolCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonPyramidCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonAllianceTreasureCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonArenaCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonDiscussCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonSupportCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonInfoCenterCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonMonumentCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonTrainHallCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonMonumentLegendCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonIntetiorCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonVipCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonPrisonCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonMasteryCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonMainMasteryCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonDrawingCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonFriendCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonBadgeBourseCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonCityDecorateCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonCityGiftCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonWallGiftCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonWarCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonMilitaryPointCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonCounterSysCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonDailySignCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonMonthGiftCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonResuscitateCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonDailyRewardCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonUnDefinedCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonPetCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonPetMapCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonSpringOfLifeCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonPremiumVipMallCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonWarGemCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonWarTechnologyCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonGodEquipmentCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonArtifactCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonPetExchangeCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonStarSpeedUpCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonProcessStudyCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonWarframeForgCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonWarframeStoreroomCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonUpStatueBraveCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonMilitaryFortressCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  void ButtonForeignPavilionCall(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch);
  public:
    static BuildingTipsHandle *Get();
    void Handle(UIBuildingTipButton* p_Ref, ui::Widget::TouchEventType p_Touch, EBuildingTips p_Op);
};