module.exports = {
    armyB_1: {
        index: 11,
        armyID: 501,
        armyId: 501,
        armyType: 2,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 116,
        barrackLevel: 1,
        starchange: 0,
        starlv: 0,
        trainingTime: 21,
        costRes: {
            Grain: 60,
            Lumber: 0,
            Iron: 0,
            Silver: 0
        },
        attack: 20,
        defense: 5,
        life: 48,
        atkInterval: 1.28,
        atkDistance: 1,
        speed: 14,
        strike: 50,
        freeWeight: 6,
        costFood: 0.05,
        power: 1,
        trainPoint: 0.001,
        trigger: 0,
        build_Speed: 0.005,
        position: 5,
        kingWarScore: 0.002,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 501,
            armyId: 501,
            armyName: "armyName_501",
            armyPic: "armyicon_b_501.png",
            armySmallPic: "armyicon_s_501.png",
            skill: [
                1311,
                1312,
                1313
            ],
            modelType: 2,
            armyDes: "",
            tip: "armtip_21",
            starchange: 0
        }
    },
    armyB_2: {
        index: 12,
        armyID: 502,
        armyId: 502,
        armyType: 2,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 116,
        barrackLevel: 4,
        starchange: 0,
        starlv: 0,
        trainingTime: 26,
        costRes: {
            Grain: 100,
            Lumber: 0,
            Iron: 0,
            Silver: 0
        },
        attack: 28,
        defense: 7,
        life: 67,
        atkInterval: 1.28,
        atkDistance: 1,
        speed: 14,
        strike: 50,
        freeWeight: 6,
        costFood: 0.1,
        power: 1.4,
        trainPoint: 0.0014,
        trigger: 0,
        build_Speed: 0.006,
        position: 5,
        kingWarScore: 0.003,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 502,
            armyId: 502,
            armyName: "armyName_502",
            armyPic: "armyicon_b_502.png",
            armySmallPic: "armyicon_s_502.png",
            skill: [
                1311,
                1312,
                1313
            ],
            modelType: 2,
            armyDes: "armyDes_502",
            tip: "armtip_21",
            starchange: 0
        }
    },
    armyB_3: {
        index: 13,
        armyID: 503,
        armyId: 503,
        armyType: 2,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 116,
        barrackLevel: 7,
        starchange: 0,
        starlv: 0,
        trainingTime: 33,
        costRes: {
            Grain: 150,
            Lumber: 0,
            Iron: 0,
            Silver: 0
        },
        attack: 38,
        defense: 9,
        life: 91,
        atkInterval: 1.28,
        atkDistance: 1,
        speed: 14,
        strike: 50,
        freeWeight: 7,
        costFood: 0.15,
        power: 1.9,
        trainPoint: 0.0019,
        trigger: 0,
        build_Speed: 0.007,
        position: 5,
        kingWarScore: 0.004,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 503,
            armyId: 503,
            armyName: "armyName_503",
            armyPic: "armyicon_b_503.png",
            armySmallPic: "armyicon_s_503.png",
            skill: [
                1311,
                1312,
                1313
            ],
            modelType: 2,
            armyDes: "armyDes_503",
            tip: "armtip_21",
            starchange: 0
        }
    },
    armyB_4: {
        index: 14,
        armyID: 504,
        armyId: 504,
        armyType: 2,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 116,
        barrackLevel: 10,
        starchange: 0,
        starlv: 0,
        trainingTime: 47,
        costRes: {
            Grain: 170,
            Lumber: 20,
            Iron: 2,
            Silver: 0
        },
        attack: 40,
        defense: 14,
        life: 121,
        atkInterval: 1.33,
        atkDistance: 4,
        speed: 13,
        strike: 50,
        freeWeight: 7,
        costFood: 0.2,
        power: 2.5,
        trainPoint: 0.0025,
        trigger: 0,
        build_Speed: 0.008,
        position: 6,
        kingWarScore: 0.005,
        GetElitePoint: 0.25,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 504,
            armyId: 504,
            armyName: "armyName_504",
            armyPic: "armyicon_b_504.png",
            armySmallPic: "armyicon_s_504.png",
            skill: [
                1311,
                1314,
                1313
            ],
            modelType: 2,
            armyDes: "armyDes_504",
            tip: "armtip_22",
            starchange: 0
        }
    },
    armyB_5: {
        index: 15,
        armyID: 505,
        armyId: 505,
        armyType: 2,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 116,
        barrackLevel: 13,
        starchange: 0,
        starlv: 0,
        trainingTime: 68,
        costRes: {
            Grain: 230,
            Lumber: 30,
            Iron: 7,
            Silver: 0
        },
        attack: 51,
        defense: 17,
        life: 154,
        atkInterval: 1.33,
        atkDistance: 4,
        speed: 13,
        strike: 50,
        freeWeight: 8,
        costFood: 0.25,
        power: 3.2,
        trainPoint: 0.0032,
        trigger: 0,
        build_Speed: 0.009,
        position: 6,
        kingWarScore: 0.006,
        GetElitePoint: 0.32,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 505,
            armyId: 505,
            armyName: "armyName_505",
            armyPic: "armyicon_b_505.png",
            armySmallPic: "armyicon_s_505.png",
            skill: [
                1311,
                1314,
                1313
            ],
            modelType: 2,
            armyDes: "armyDes_505",
            tip: "armtip_22",
            starchange: 0
        }
    },
    armyB_6: {
        index: 16,
        armyID: 506,
        armyId: 506,
        armyType: 2,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 116,
        barrackLevel: 16,
        starchange: 0,
        starlv: 0,
        trainingTime: 84,
        costRes: {
            Grain: 300,
            Lumber: 60,
            Iron: 15,
            Silver: 0
        },
        attack: 80,
        defense: 20,
        life: 192,
        atkInterval: 1.28,
        atkDistance: 1,
        speed: 14,
        strike: 50,
        freeWeight: 8,
        costFood: 0.3,
        power: 4,
        trainPoint: 0.004,
        trigger: 0,
        build_Speed: 0.01,
        position: 5,
        kingWarScore: 0.007,
        GetElitePoint: 0.4,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 506,
            armyId: 506,
            armyName: "armyName_506",
            armyPic: "armyicon_b_506.png",
            armySmallPic: "armyicon_s_506.png",
            skill: [
                1311,
                1312,
                1313
            ],
            modelType: 2,
            armyDes: "armyDes_506",
            tip: "armtip_21",
            starchange: 0
        }
    },
    armyB_7: {
        index: 17,
        armyID: 507,
        armyId: 507,
        armyType: 2,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 116,
        barrackLevel: 19,
        starchange: 0,
        starlv: 0,
        trainingTime: 105,
        costRes: {
            Grain: 340,
            Lumber: 70,
            Iron: 20,
            Silver: 5
        },
        attack: 80,
        defense: 30,
        life: 271,
        atkInterval: 1.33,
        atkDistance: 4,
        speed: 13,
        strike: 50,
        freeWeight: 9,
        costFood: 0.35,
        power: 4.9,
        trainPoint: 0.0049,
        trigger: 0,
        build_Speed: 0.011,
        position: 6,
        kingWarScore: 0.008,
        GetElitePoint: 0.49,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 507,
            armyId: 507,
            armyName: "armyName_507",
            armyPic: "armyicon_b_507.png",
            armySmallPic: "armyicon_s_507.png",
            skill: [
                1311,
                1314,
                1313
            ],
            modelType: 2,
            armyDes: "armyDes_507",
            tip: "armtip_22",
            starchange: 0
        }
    },
    armyB_8: {
        index: 18,
        armyID: 508,
        armyId: 508,
        armyType: 2,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 116,
        barrackLevel: 22,
        starchange: 0,
        starlv: 0,
        trainingTime: 126,
        costRes: {
            Grain: 400,
            Lumber: 100,
            Iron: 35,
            Silver: 8
        },
        attack: 100,
        defense: 40,
        life: 300,
        atkInterval: 1.28,
        atkDistance: 1,
        speed: 14,
        strike: 50,
        freeWeight: 9,
        costFood: 0.4,
        power: 5.9,
        trainPoint: 0.0059,
        trigger: 0,
        build_Speed: 0.012,
        position: 5,
        kingWarScore: 0.009,
        GetElitePoint: 0.59,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 508,
            armyId: 508,
            armyName: "armyName_508",
            armyPic: "armyicon_b_508.png",
            armySmallPic: "armyicon_s_508.png",
            skill: [
                1311,
                1312,
                1313
            ],
            modelType: 2,
            armyDes: "armyDes_508",
            tip: "armtip_21",
            starchange: 0
        }
    },
    armyB_9: {
        index: 19,
        armyID: 509,
        armyId: 509,
        armyType: 2,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 116,
        barrackLevel: 26,
        starchange: 0,
        starlv: 0,
        trainingTime: 152,
        costRes: {
            Grain: 550,
            Lumber: 150,
            Iron: 40,
            Silver: 11
        },
        attack: 110,
        defense: 40,
        life: 360,
        atkInterval: 1.33,
        atkDistance: 4,
        speed: 13,
        strike: 50,
        freeWeight: 10,
        costFood: 0.45,
        power: 7,
        trainPoint: 0.007,
        trigger: 0,
        build_Speed: 0.013,
        position: 6,
        kingWarScore: 0.01,
        GetElitePoint: 0.7,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 509,
            armyId: 509,
            armyName: "armyName_509",
            armyPic: "armyicon_b_509.png",
            armySmallPic: "armyicon_s_509.png",
            skill: [
                1311,
                1314,
                1313
            ],
            modelType: 2,
            armyDes: "armyDes_509",
            tip: "armtip_22",
            starchange: 0
        }
    },
    armyB_10: {
        index: 20,
        armyID: 510,
        armyId: 510,
        armyType: 2,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 116,
        barrackLevel: 30,
        starchange: 0,
        starlv: 0,
        trainingTime: 189,
        costRes: {
            Grain: 700,
            Lumber: 240,
            Iron: 50,
            Silver: 15
        },
        attack: 164,
        defense: 41,
        life: 393,
        atkInterval: 1.28,
        atkDistance: 1,
        speed: 14,
        strike: 50,
        freeWeight: 10,
        costFood: 0.5,
        power: 8.2,
        trainPoint: 0.0082,
        trigger: 0,
        build_Speed: 0.014,
        position: 5,
        kingWarScore: 0.011,
        GetElitePoint: 0.82,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 510,
            armyId: 510,
            armyName: "armyName_510",
            armyPic: "armyicon_b_510.png",
            armySmallPic: "armyicon_s_510.png",
            skill: [
                1311,
                1312,
                1313
            ],
            modelType: 2,
            armyDes: "armyDes_510",
            tip: "armtip_21",
            starchange: 0
        }
    },
    armyB_11: {
        index: 242,
        armyID: 10004511,
        armyId: 511,
        armyType: 2,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 116,
        barrackLevel: 80,
        starchange: 0,
        starlv: 0,
        trainingTime: 225,
        costRes: {
            Grain: 850,
            Lumber: 350,
            Iron: 70,
            Silver: 25,
            Crystal: 0
        },
        attack: 165,
        defense: 55,
        life: 500,
        atkInterval: 1.33,
        atkDistance: 4,
        speed: 13,
        strike: 50,
        freeWeight: 11,
        costFood: 0.55,
        power: 10.5,
        trainPoint: 0.0105,
        trigger: 0,
        build_Speed: 0.015,
        position: 6,
        kingWarScore: 0.012,
        GetElitePoint: 1.05,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 10004511,
            armyId: 511,
            armyName: "armyName_10004511",
            armyPic: "armyicon_b_10004511.png",
            armySmallPic: "armyicon_s_10004511.png",
            skill: [
                10221311,
                10211314,
                10211313,
                10241326
            ],
            modelType: 2,
            armyDes: "armyDes_10004511",
            tip: "armtip_22",
            starchange: 17
        }
    },
    armyB_12: {
        index: 550,
        armyID: 1710007511,
        armyId: 512,
        armyType: 2,
        armorType: 0,
        battleUnitType: 6,
        barrackID: 116,
        barrackLevel: 110,
        starchange: 0,
        starlv: 17,
        trainingTime: 225,
        costRes: {
            Grain: 850,
            Lumber: 350,
            Iron: 70,
            Silver: 25,
            Crystal: 0
        },
        attack: 184,
        defense: 66,
        life: 524,
        atkInterval: 1.33,
        atkDistance: 4,
        speed: 13,
        strike: 50,
        freeWeight: 12,
        costFood: 0.57,
        power: 12,
        trainPoint: 0.012,
        trigger: 0,
        build_Speed: 0.015,
        position: 6,
        kingWarScore: 0.012,
        GetElitePoint: 1.2,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 1710007511,
            armyId: 512,
            armyName: "soldier_name_06",
            armyPic: "armyicon_b_1710007511.png",
            armySmallPic: "armyicon_s_1710007511.png",
            skill: [
                10231356,
                10231312,
                10231314,
                1348
            ],
            modelType: 2,
            armyDes: "armyDes_10007511",
            tip: "armtip_22",
            starchange: 0
        }
    },
    armyB_13: {
        index: 1214,
        armyID: 5810009512,
        armyId: 513,
        armyType: 2,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 116,
        barrackLevel: 130,
        starchange: 0,
        starlv: 58,
        trainingTime: 315,
        costRes: {
            Grain: 1000,
            Lumber: 460,
            Iron: 100,
            Silver: 40,
            Crystal: 20
        },
        attack: 281,
        defense: 91,
        life: 721,
        atkInterval: 1.28,
        atkDistance: 1,
        speed: 14,
        strike: 50,
        freeWeight: 14,
        costFood: 0.63,
        power: 15,
        trainPoint: 0.015,
        trigger: 0,
        build_Speed: 0.017,
        position: 5,
        kingWarScore: 0.015,
        GetElitePoint: 1.5,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 5810009512,
            armyId: 513,
            armyName: "soldier_name_10",
            armyPic: "armyicon_b_5810009512.png",
            armySmallPic: "armyicon_s_5810009512.png",
            skill: [
                10241301,
                10241311,
                10241313,
                1351
            ],
            modelType: 2,
            armyDes: "armyDes_10009512",
            tip: "armtip_21",
            starchange: 0
        }
    },
    armyB_14: {
        index: 1336,
        armyID: 7010009513,
        armyId: 514,
        armyType: 2,
        armorType: 1,
        battleUnitType: 0,
        barrackID: 116,
        barrackLevel: 130,
        starchange: 0,
        starlv: 70,
        trainingTime: 335,
        costRes: {
            1620: 8,
            Grain: 1000,
            Lumber: 460,
            Iron: 100,
            Silver: 40,
            Crystal: 20
        },
        attack: 400,
        defense: 120,
        life: 2003,
        atkInterval: 1.28,
        atkDistance: 1,
        speed: 14,
        strike: 50,
        freeWeight: 16,
        costFood: 0.65,
        power: 22,
        trainPoint: 0.022,
        trigger: 0,
        build_Speed: 0.018,
        position: 5,
        kingWarScore: 0.02,
        GetElitePoint: 2.2,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 7010009513,
            armyId: 514,
            armyName: "soldier_name_14",
            armyPic: "armyicon_b_10009513.png",
            armySmallPic: "armyicon_s_10009513.png",
            skill: [
                10251363,
                10251369,
                10251364,
                10251367
            ],
            modelType: 2,
            armyDes: "armyDes_10009713",
            tip: "armtip_21",
            starchange: 0
        }
    }
};