module.exports = {
    armyTrapA_1: {
        index: 41,
        armyID: 801,
        armyId: 801,
        armyType: 9,
        armorType: 0,
        battleUnitType: 5,
        barrackID: 120,
        barrackLevel: 1,
        starchange: 0,
        starlv: 0,
        trainingTime: 25,
        costRes: {
            Grain: 250,
            Lumber: 0,
            Iron: 0,
            Silver: 0
        },
        attack: 80,
        defense: 0,
        life: 0,
        atkInterval: 0,
        atkDistance: 1,
        speed: 0,
        strike: 0,
        freeWeight: 0,
        costFood: 0,
        power: 1,
        trainPoint: 0.001,
        trigger: 80,
        build_Speed: 0,
        position: 0,
        kingWarScore: 0,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 801,
            armyId: 801,
            armyName: {
                name: "armyName_801",
                num: 1
            },
            armyPic: "armyicon_xj_801.png",
            armySmallPic: "armyicon_xj_801.png",
            skill: [
                1321,
                1322
            ],
            modelType: 0,
            armyDes: "armyDes_800",
            tip: "armtip_51",
            starchange: 0
        }
    },
    armyTrapA_2: {
        index: 44,
        armyID: 802,
        armyId: 802,
        armyType: 9,
        armorType: 0,
        battleUnitType: 5,
        barrackID: 120,
        barrackLevel: 6,
        starchange: 0,
        starlv: 0,
        trainingTime: 40,
        costRes: {
            Grain: 500,
            Lumber: 0,
            Iron: 0,
            Silver: 0
        },
        attack: 200,
        defense: 0,
        life: 0,
        atkInterval: 0,
        atkDistance: 1,
        speed: 0,
        strike: 0,
        freeWeight: 0,
        costFood: 0,
        power: 2.5,
        trainPoint: 0.0025,
        trigger: 100,
        build_Speed: 0,
        position: 0,
        kingWarScore: 0,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 802,
            armyId: 802,
            armyName: {
                name: "armyName_801",
                num: 2
            },
            armyPic: "armyicon_xj_802.png",
            armySmallPic: "armyicon_xj_802.png",
            skill: [
                1321,
                1322
            ],
            modelType: 0,
            armyDes: "armyDes_800",
            tip: "armtip_51",
            starchange: 0
        }
    },
    armyTrapA_3: {
        index: 47,
        armyID: 803,
        armyId: 803,
        armyType: 9,
        armorType: 0,
        battleUnitType: 5,
        barrackID: 120,
        barrackLevel: 12,
        starchange: 0,
        starlv: 0,
        trainingTime: 70,
        costRes: {
            Grain: 600,
            Lumber: 0,
            Iron: 80,
            Silver: 0
        },
        attack: 320,
        defense: 0,
        life: 0,
        atkInterval: 0,
        atkDistance: 1,
        speed: 0,
        strike: 0,
        freeWeight: 0,
        costFood: 0,
        power: 4,
        trainPoint: 0.004,
        trigger: 120,
        build_Speed: 0,
        position: 0,
        kingWarScore: 0,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 803,
            armyId: 803,
            armyName: {
                name: "armyName_801",
                num: 3
            },
            armyPic: "armyicon_xj_803.png",
            armySmallPic: "armyicon_xj_803.png",
            skill: [
                1321,
                1322
            ],
            modelType: 0,
            armyDes: "armyDes_800",
            tip: "armtip_51",
            starchange: 0
        }
    },
    armyTrapA_4: {
        index: 50,
        armyID: 804,
        armyId: 804,
        armyType: 9,
        armorType: 0,
        battleUnitType: 5,
        barrackID: 120,
        barrackLevel: 18,
        starchange: 0,
        starlv: 0,
        trainingTime: 130,
        costRes: {
            Grain: 700,
            Lumber: 0,
            Iron: 80,
            Silver: 20
        },
        attack: 440,
        defense: 0,
        life: 0,
        atkInterval: 0,
        atkDistance: 1,
        speed: 0,
        strike: 0,
        freeWeight: 0,
        costFood: 0,
        power: 5.5,
        trainPoint: 0.0055,
        trigger: 140,
        build_Speed: 0,
        position: 0,
        kingWarScore: 0,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 804,
            armyId: 804,
            armyName: {
                name: "armyName_801",
                num: 4
            },
            armyPic: "armyicon_xj_804.png",
            armySmallPic: "armyicon_xj_804.png",
            skill: [
                1321,
                1322
            ],
            modelType: 0,
            armyDes: "armyDes_800",
            tip: "armtip_51",
            starchange: 0
        }
    },
    armyTrapA_5: {
        index: 53,
        armyID: 805,
        armyId: 805,
        armyType: 9,
        armorType: 0,
        battleUnitType: 5,
        barrackID: 120,
        barrackLevel: 24,
        starchange: 0,
        starlv: 0,
        trainingTime: 250,
        costRes: {
            Grain: 950,
            Lumber: 0,
            Iron: 100,
            Silver: 25
        },
        attack: 600,
        defense: 0,
        life: 0,
        atkInterval: 0,
        atkDistance: 1,
        speed: 0,
        strike: 0,
        freeWeight: 0,
        costFood: 0,
        power: 7.5,
        trainPoint: 0.0075,
        trigger: 160,
        build_Speed: 0,
        position: 0,
        kingWarScore: 0,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 805,
            armyId: 805,
            armyName: {
                name: "armyName_801",
                num: 5
            },
            armyPic: "armyicon_xj_805.png",
            armySmallPic: "armyicon_xj_805.png",
            skill: [
                1321,
                1322
            ],
            modelType: 0,
            armyDes: "armyDes_800",
            tip: "armtip_51",
            starchange: 0
        }
    },
    armyTrapB_1: {
        index: 42,
        armyID: 811,
        armyId: 811,
        armyType: 9,
        armorType: 0,
        battleUnitType: 6,
        barrackID: 120,
        barrackLevel: 2,
        starchange: 0,
        starlv: 0,
        trainingTime: 25,
        costRes: {
            Grain: 125,
            Lumber: 125,
            Iron: 0,
            Silver: 0
        },
        attack: 80,
        defense: 0,
        life: 0,
        atkInterval: 0,
        atkDistance: 1,
        speed: 0,
        strike: 0,
        freeWeight: 0,
        costFood: 0,
        power: 1,
        trainPoint: 0.001,
        trigger: 80,
        build_Speed: 0,
        position: 0,
        kingWarScore: 0,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 811,
            armyId: 811,
            armyName: {
                name: "armyName_811",
                num: 1
            },
            armyPic: "armyicon_xj_811.png",
            armySmallPic: "armyicon_xj_811.png",
            skill: [
                1321,
                1323
            ],
            modelType: 0,
            armyDes: "armyDes_810",
            tip: "armtip_51",
            starchange: 0
        }
    },
    armyTrapB_2: {
        index: 45,
        armyID: 812,
        armyId: 812,
        armyType: 9,
        armorType: 0,
        battleUnitType: 6,
        barrackID: 120,
        barrackLevel: 8,
        starchange: 0,
        starlv: 0,
        trainingTime: 40,
        costRes: {
            Grain: 250,
            Lumber: 250,
            Iron: 0,
            Silver: 0
        },
        attack: 200,
        defense: 0,
        life: 0,
        atkInterval: 0,
        atkDistance: 1,
        speed: 0,
        strike: 0,
        freeWeight: 0,
        costFood: 0,
        power: 2.5,
        trainPoint: 0.0025,
        trigger: 100,
        build_Speed: 0,
        position: 0,
        kingWarScore: 0,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 812,
            armyId: 812,
            armyName: {
                name: "armyName_811",
                num: 2
            },
            armyPic: "armyicon_xj_812.png",
            armySmallPic: "armyicon_xj_812.png",
            skill: [
                1321,
                1323
            ],
            modelType: 0,
            armyDes: "armyDes_810",
            tip: "armtip_51",
            starchange: 0
        }
    },
    armyTrapB_3: {
        index: 48,
        armyID: 813,
        armyId: 813,
        armyType: 9,
        armorType: 0,
        battleUnitType: 6,
        barrackID: 120,
        barrackLevel: 14,
        starchange: 0,
        starlv: 0,
        trainingTime: 70,
        costRes: {
            Grain: 300,
            Lumber: 300,
            Iron: 80,
            Silver: 0
        },
        attack: 320,
        defense: 0,
        life: 0,
        atkInterval: 0,
        atkDistance: 1,
        speed: 0,
        strike: 0,
        freeWeight: 0,
        costFood: 0,
        power: 4,
        trainPoint: 0.004,
        trigger: 120,
        build_Speed: 0,
        position: 0,
        kingWarScore: 0,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 813,
            armyId: 813,
            armyName: {
                name: "armyName_811",
                num: 3
            },
            armyPic: "armyicon_xj_813.png",
            armySmallPic: "armyicon_xj_813.png",
            skill: [
                1321,
                1323
            ],
            modelType: 0,
            armyDes: "armyDes_810",
            tip: "armtip_51",
            starchange: 0
        }
    },
    armyTrapB_4: {
        index: 51,
        armyID: 814,
        armyId: 814,
        armyType: 9,
        armorType: 0,
        battleUnitType: 6,
        barrackID: 120,
        barrackLevel: 20,
        starchange: 0,
        starlv: 0,
        trainingTime: 130,
        costRes: {
            Grain: 350,
            Lumber: 350,
            Iron: 80,
            Silver: 20
        },
        attack: 440,
        defense: 0,
        life: 0,
        atkInterval: 0,
        atkDistance: 1,
        speed: 0,
        strike: 0,
        freeWeight: 0,
        costFood: 0,
        power: 5.5,
        trainPoint: 0.0055,
        trigger: 140,
        build_Speed: 0,
        position: 0,
        kingWarScore: 0,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 814,
            armyId: 814,
            armyName: {
                name: "armyName_811",
                num: 4
            },
            armyPic: "armyicon_xj_814.png",
            armySmallPic: "armyicon_xj_814.png",
            skill: [
                1321,
                1323
            ],
            modelType: 0,
            armyDes: "armyDes_810",
            tip: "armtip_51",
            starchange: 0
        }
    },
    armyTrapB_5: {
        index: 54,
        armyID: 815,
        armyId: 815,
        armyType: 9,
        armorType: 0,
        battleUnitType: 6,
        barrackID: 120,
        barrackLevel: 27,
        starchange: 0,
        starlv: 0,
        trainingTime: 250,
        costRes: {
            Grain: 475,
            Lumber: 475,
            Iron: 100,
            Silver: 25
        },
        attack: 600,
        defense: 0,
        life: 0,
        atkInterval: 0,
        atkDistance: 1,
        speed: 0,
        strike: 0,
        freeWeight: 0,
        costFood: 0,
        power: 7.5,
        trainPoint: 0.0075,
        trigger: 160,
        build_Speed: 0,
        position: 0,
        kingWarScore: 0,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 815,
            armyId: 815,
            armyName: {
                name: "armyName_811",
                num: 5
            },
            armyPic: "armyicon_xj_815.png",
            armySmallPic: "armyicon_xj_815.png",
            skill: [
                1321,
                1323
            ],
            modelType: 0,
            armyDes: "armyDes_810",
            tip: "armtip_51",
            starchange: 0
        }
    },
    armyTrapC_1: {
        index: 43,
        armyID: 821,
        armyId: 821,
        armyType: 9,
        armorType: 0,
        battleUnitType: 7,
        barrackID: 120,
        barrackLevel: 3,
        starchange: 0,
        starlv: 0,
        trainingTime: 25,
        costRes: {
            Grain: 0,
            Lumber: 250,
            Iron: 0,
            Silver: 0
        },
        attack: 80,
        defense: 0,
        life: 0,
        atkInterval: 0,
        atkDistance: 1,
        speed: 0,
        strike: 0,
        freeWeight: 0,
        costFood: 0,
        power: 1,
        trainPoint: 0.001,
        trigger: 80,
        build_Speed: 0,
        position: 0,
        kingWarScore: 0,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 821,
            armyId: 821,
            armyName: {
                name: "armyName_821",
                num: 1
            },
            armyPic: "armyicon_xj_821.png",
            armySmallPic: "armyicon_xj_821.png",
            skill: [
                1321,
                1324
            ],
            modelType: 0,
            armyDes: "armyDes_820",
            tip: "armtip_51",
            starchange: 0
        }
    },
    armyTrapC_2: {
        index: 46,
        armyID: 822,
        armyId: 822,
        armyType: 9,
        armorType: 0,
        battleUnitType: 7,
        barrackID: 120,
        barrackLevel: 10,
        starchange: 0,
        starlv: 0,
        trainingTime: 40,
        costRes: {
            Grain: 0,
            Lumber: 500,
            Iron: 0,
            Silver: 0
        },
        attack: 200,
        defense: 0,
        life: 0,
        atkInterval: 0,
        atkDistance: 1,
        speed: 0,
        strike: 0,
        freeWeight: 0,
        costFood: 0,
        power: 2.5,
        trainPoint: 0.0025,
        trigger: 100,
        build_Speed: 0,
        position: 0,
        kingWarScore: 0,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 822,
            armyId: 822,
            armyName: {
                name: "armyName_821",
                num: 2
            },
            armyPic: "armyicon_xj_822.png",
            armySmallPic: "armyicon_xj_822.png",
            skill: [
                1321,
                1324
            ],
            modelType: 0,
            armyDes: "armyDes_820",
            tip: "armtip_51",
            starchange: 0
        }
    },
    armyTrapC_3: {
        index: 49,
        armyID: 823,
        armyId: 823,
        armyType: 9,
        armorType: 0,
        battleUnitType: 7,
        barrackID: 120,
        barrackLevel: 16,
        starchange: 0,
        starlv: 0,
        trainingTime: 70,
        costRes: {
            Grain: 0,
            Lumber: 600,
            Iron: 80,
            Silver: 0
        },
        attack: 320,
        defense: 0,
        life: 0,
        atkInterval: 0,
        atkDistance: 1,
        speed: 0,
        strike: 0,
        freeWeight: 0,
        costFood: 0,
        power: 4,
        trainPoint: 0.004,
        trigger: 120,
        build_Speed: 0,
        position: 0,
        kingWarScore: 0,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 823,
            armyId: 823,
            armyName: {
                name: "armyName_821",
                num: 3
            },
            armyPic: "armyicon_xj_823.png",
            armySmallPic: "armyicon_xj_823.png",
            skill: [
                1321,
                1324
            ],
            modelType: 0,
            armyDes: "armyDes_820",
            tip: "armtip_51",
            starchange: 0
        }
    },
    armyTrapC_4: {
        index: 52,
        armyID: 824,
        armyId: 824,
        armyType: 9,
        armorType: 0,
        battleUnitType: 7,
        barrackID: 120,
        barrackLevel: 22,
        starchange: 0,
        starlv: 0,
        trainingTime: 130,
        costRes: {
            Grain: 0,
            Lumber: 700,
            Iron: 80,
            Silver: 20
        },
        attack: 440,
        defense: 0,
        life: 0,
        atkInterval: 0,
        atkDistance: 1,
        speed: 0,
        strike: 0,
        freeWeight: 0,
        costFood: 0,
        power: 5.5,
        trainPoint: 0.0055,
        trigger: 140,
        build_Speed: 0,
        position: 0,
        kingWarScore: 0,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 824,
            armyId: 824,
            armyName: {
                name: "armyName_821",
                num: 4
            },
            armyPic: "armyicon_xj_824.png",
            armySmallPic: "armyicon_xj_824.png",
            skill: [
                1321,
                1324
            ],
            modelType: 0,
            armyDes: "armyDes_820",
            tip: "armtip_51",
            starchange: 0
        }
    },
    armyTrapC_5: {
        index: 55,
        armyID: 825,
        armyId: 825,
        armyType: 9,
        armorType: 0,
        battleUnitType: 7,
        barrackID: 120,
        barrackLevel: 30,
        starchange: 0,
        starlv: 0,
        trainingTime: 250,
        costRes: {
            Grain: 0,
            Lumber: 950,
            Iron: 100,
            Silver: 25
        },
        attack: 600,
        defense: 0,
        life: 0,
        atkInterval: 0,
        atkDistance: 1,
        speed: 0,
        strike: 0,
        freeWeight: 0,
        costFood: 0,
        power: 7.5,
        trainPoint: 0.0075,
        trigger: 160,
        build_Speed: 0,
        position: 0,
        kingWarScore: 0,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 825,
            armyId: 825,
            armyName: {
                name: "armyName_821",
                num: 5
            },
            armyPic: "armyicon_xj_825.png",
            armySmallPic: "armyicon_xj_825.png",
            skill: [
                1321,
                1324
            ],
            modelType: 0,
            armyDes: "armyDes_820",
            tip: "armtip_51",
            starchange: 0
        }
    }
};