module.exports = {
    armyC_1: {
        index: 21,
        armyID: 601,
        armyId: 601,
        armyType: 3,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 117,
        barrackLevel: 1,
        starchange: 0,
        starlv: 0,
        trainingTime: 22,
        costRes: {
            Grain: 60,
            Lumber: 0,
            Iron: 0,
            Silver: 0
        },
        attack: 17,
        defense: 4,
        life: 37,
        atkInterval: 1,
        atkDistance: 5,
        speed: 8,
        strike: 50,
        freeWeight: 8,
        costFood: 0.05,
        power: 1,
        trainPoint: 0.001,
        trigger: 0,
        build_Speed: 0.005,
        position: 7,
        kingWarScore: 0.002,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 601,
            armyId: 601,
            armyName: "armyName_601",
            armyPic: "armyicon_b_601.png",
            armySmallPic: "armyicon_s_601.png",
            skill: [
                1307,
                1308
            ],
            modelType: 3,
            armyDes: "",
            tip: "armtip_31",
            starchange: 0
        }
    },
    armyC_2: {
        index: 22,
        armyID: 602,
        armyId: 602,
        armyType: 3,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 117,
        barrackLevel: 4,
        starchange: 0,
        starlv: 0,
        trainingTime: 27,
        costRes: {
            Grain: 90,
            Lumber: 10,
            Iron: 0,
            Silver: 0
        },
        attack: 23,
        defense: 5,
        life: 51,
        atkInterval: 1,
        atkDistance: 5,
        speed: 8,
        strike: 50,
        freeWeight: 8,
        costFood: 0.1,
        power: 1.4,
        trainPoint: 0.0014,
        trigger: 0,
        build_Speed: 0.006,
        position: 7,
        kingWarScore: 0.003,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 602,
            armyId: 602,
            armyName: "armyName_602",
            armyPic: "armyicon_b_602.png",
            armySmallPic: "armyicon_s_602.png",
            skill: [
                1307,
                1308
            ],
            modelType: 3,
            armyDes: "armyDes_602",
            tip: "armtip_31",
            starchange: 0
        }
    },
    armyC_3: {
        index: 23,
        armyID: 603,
        armyId: 603,
        armyType: 3,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 117,
        barrackLevel: 7,
        starchange: 0,
        starlv: 0,
        trainingTime: 35,
        costRes: {
            Grain: 130,
            Lumber: 20,
            Iron: 0,
            Silver: 0
        },
        attack: 28,
        defense: 8,
        life: 85,
        atkInterval: 1.33,
        atkDistance: 8,
        speed: 8,
        strike: 200,
        freeWeight: 8,
        costFood: 0.15,
        power: 1.9,
        trainPoint: 0.0019,
        trigger: 0,
        build_Speed: 0.007,
        position: 8,
        kingWarScore: 0.004,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 603,
            armyId: 603,
            armyName: "armyName_603",
            armyPic: "armyicon_b_603.png",
            armySmallPic: "armyicon_s_603.png",
            skill: [
                1309,
                1305
            ],
            modelType: 3,
            armyDes: "armyDes_603",
            tip: "armtip_32",
            starchange: 0
        }
    },
    armyC_4: {
        index: 24,
        armyID: 604,
        armyId: 604,
        armyType: 3,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 117,
        barrackLevel: 10,
        starchange: 0,
        starlv: 0,
        trainingTime: 49,
        costRes: {
            Grain: 170,
            Lumber: 20,
            Iron: 2,
            Silver: 0
        },
        attack: 36,
        defense: 10,
        life: 111,
        atkInterval: 1.33,
        atkDistance: 8,
        speed: 8,
        strike: 200,
        freeWeight: 8,
        costFood: 0.2,
        power: 2.5,
        trainPoint: 0.0025,
        trigger: 0,
        build_Speed: 0.008,
        position: 8,
        kingWarScore: 0.005,
        GetElitePoint: 0.25,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 604,
            armyId: 604,
            armyName: "armyName_604",
            armyPic: "armyicon_b_604.png",
            armySmallPic: "armyicon_s_604.png",
            skill: [
                1309,
                1305
            ],
            modelType: 3,
            armyDes: "armyDes_604",
            tip: "armtip_32",
            starchange: 0
        }
    },
    armyC_5: {
        index: 25,
        armyID: 605,
        armyId: 605,
        armyType: 3,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 117,
        barrackLevel: 13,
        starchange: 0,
        starlv: 0,
        trainingTime: 71,
        costRes: {
            Grain: 250,
            Lumber: 25,
            Iron: 4,
            Silver: 0
        },
        attack: 54,
        defense: 12,
        life: 118,
        atkInterval: 1,
        atkDistance: 5,
        speed: 8,
        strike: 50,
        freeWeight: 10,
        costFood: 0.25,
        power: 3.2,
        trainPoint: 0.0032,
        trigger: 0,
        build_Speed: 0.009,
        position: 7,
        kingWarScore: 0.006,
        GetElitePoint: 0.32,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 605,
            armyId: 605,
            armyName: "armyName_605",
            armyPic: "armyicon_b_605.png",
            armySmallPic: "armyicon_s_605.png",
            skill: [
                1307,
                1308
            ],
            modelType: 3,
            armyDes: "armyDes_605",
            tip: "armtip_31",
            starchange: 0
        }
    },
    armyC_6: {
        index: 26,
        armyID: 606,
        armyId: 606,
        armyType: 3,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 117,
        barrackLevel: 16,
        starchange: 0,
        starlv: 0,
        trainingTime: 88,
        costRes: {
            Grain: 340,
            Lumber: 50,
            Iron: 10,
            Silver: 0
        },
        attack: 68,
        defense: 16,
        life: 148,
        atkInterval: 1,
        atkDistance: 5,
        speed: 8,
        strike: 50,
        freeWeight: 10,
        costFood: 0.3,
        power: 4,
        trainPoint: 0.004,
        trigger: 0,
        build_Speed: 0.01,
        position: 7,
        kingWarScore: 0.007,
        GetElitePoint: 0.4,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 606,
            armyId: 606,
            armyName: "armyName_606",
            armyPic: "armyicon_b_606.png",
            armySmallPic: "armyicon_s_606.png",
            skill: [
                1307,
                1308
            ],
            modelType: 3,
            armyDes: "armyDes_606",
            tip: "armtip_31",
            starchange: 0
        }
    },
    armyC_7: {
        index: 27,
        armyID: 607,
        armyId: 607,
        armyType: 3,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 117,
        barrackLevel: 19,
        starchange: 0,
        starlv: 0,
        trainingTime: 110,
        costRes: {
            Grain: 450,
            Lumber: 60,
            Iron: 15,
            Silver: 2
        },
        attack: 90,
        defense: 25,
        life: 210,
        atkInterval: 1.33,
        atkDistance: 8,
        speed: 8,
        strike: 200,
        freeWeight: 10,
        costFood: 0.35,
        power: 4.9,
        trainPoint: 0.0049,
        trigger: 0,
        build_Speed: 0.011,
        position: 8,
        kingWarScore: 0.008,
        GetElitePoint: 0.49,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 607,
            armyId: 607,
            armyName: "armyName_607",
            armyPic: "armyicon_b_607.png",
            armySmallPic: "armyicon_s_607.png",
            skill: [
                1309,
                1305
            ],
            modelType: 3,
            armyDes: "armyDes_607",
            tip: "armtip_32",
            starchange: 0
        }
    },
    armyC_8: {
        index: 28,
        armyID: 608,
        armyId: 608,
        armyType: 3,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 117,
        barrackLevel: 22,
        starchange: 0,
        starlv: 0,
        trainingTime: 132,
        costRes: {
            Grain: 600,
            Lumber: 110,
            Iron: 20,
            Silver: 3
        },
        attack: 100,
        defense: 30,
        life: 230,
        atkInterval: 1,
        atkDistance: 5,
        speed: 8,
        strike: 50,
        freeWeight: 11,
        costFood: 0.4,
        power: 5.9,
        trainPoint: 0.0059,
        trigger: 0,
        build_Speed: 0.012,
        position: 7,
        kingWarScore: 0.009,
        GetElitePoint: 0.59,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 608,
            armyId: 608,
            armyName: "armyName_608",
            armyPic: "armyicon_b_608.png",
            armySmallPic: "armyicon_s_608.png",
            skill: [
                1307,
                1308
            ],
            modelType: 3,
            armyDes: "armyDes_608",
            tip: "armtip_31",
            starchange: 0
        }
    },
    armyC_9: {
        index: 29,
        armyID: 609,
        armyId: 609,
        armyType: 3,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 117,
        barrackLevel: 26,
        starchange: 0,
        starlv: 0,
        trainingTime: 159,
        costRes: {
            Grain: 800,
            Lumber: 150,
            Iron: 25,
            Silver: 4
        },
        attack: 118,
        defense: 30,
        life: 289,
        atkInterval: 1.33,
        atkDistance: 8,
        speed: 8,
        strike: 200,
        freeWeight: 11,
        costFood: 0.45,
        power: 7,
        trainPoint: 0.007,
        trigger: 0,
        build_Speed: 0.013,
        position: 8,
        kingWarScore: 0.01,
        GetElitePoint: 0.7,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 609,
            armyId: 609,
            armyName: "armyName_609",
            armyPic: "armyicon_b_609.png",
            armySmallPic: "armyicon_s_609.png",
            skill: [
                1309,
                1305
            ],
            modelType: 3,
            armyDes: "armyDes_609",
            tip: "armtip_32",
            starchange: 0
        }
    },
    armyC_10: {
        index: 30,
        armyID: 610,
        armyId: 610,
        armyType: 3,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 117,
        barrackLevel: 30,
        starchange: 0,
        starlv: 0,
        trainingTime: 198,
        costRes: {
            Grain: 1000,
            Lumber: 300,
            Iron: 30,
            Silver: 5
        },
        attack: 139,
        defense: 32,
        life: 303,
        atkInterval: 1,
        atkDistance: 5,
        speed: 8,
        strike: 50,
        freeWeight: 12,
        costFood: 0.5,
        power: 8.2,
        trainPoint: 0.0082,
        trigger: 0,
        build_Speed: 0.014,
        position: 7,
        kingWarScore: 0.011,
        GetElitePoint: 0.82,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 610,
            armyId: 610,
            armyName: "armyName_610",
            armyPic: "armyicon_b_610.png",
            armySmallPic: "armyicon_s_610.png",
            skill: [
                1307,
                1308
            ],
            modelType: 3,
            armyDes: "armyDes_610",
            tip: "armtip_31",
            starchange: 0
        }
    },
    armyC_11: {
        index: 253,
        armyID: 10004611,
        armyId: 611,
        armyType: 3,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 117,
        barrackLevel: 80,
        starchange: 0,
        starlv: 0,
        trainingTime: 230,
        costRes: {
            Grain: 1100,
            Lumber: 400,
            Iron: 60,
            Silver: 15,
            Crystal: 0
        },
        attack: 145,
        defense: 45,
        life: 450,
        atkInterval: 1.33,
        atkDistance: 8,
        speed: 8,
        strike: 200,
        freeWeight: 12,
        costFood: 0.55,
        power: 10.5,
        trainPoint: 0.0105,
        trigger: 0,
        build_Speed: 0.015,
        position: 8,
        kingWarScore: 0.012,
        GetElitePoint: 1.05,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 10004611,
            armyId: 611,
            armyName: "armyName_10004611",
            armyPic: "armyicon_b_10004611.png",
            armySmallPic: "armyicon_s_10004611.png",
            skill: [
                10211309,
                10211305,
                10241327
            ],
            modelType: 3,
            armyDes: "armyDes_10004611",
            tip: "armtip_32",
            starchange: 17
        }
    },
    armyC_12: {
        index: 551,
        armyID: 1710007611,
        armyId: 612,
        armyType: 3,
        armorType: 0,
        battleUnitType: 8,
        barrackID: 117,
        barrackLevel: 110,
        starchange: 0,
        starlv: 17,
        trainingTime: 230,
        costRes: {
            Grain: 1100,
            Lumber: 400,
            Iron: 60,
            Silver: 15,
            Crystal: 0
        },
        attack: 208,
        defense: 62,
        life: 494,
        atkInterval: 1.33,
        atkDistance: 8,
        speed: 8,
        strike: 200,
        freeWeight: 12,
        costFood: 0.57,
        power: 12,
        trainPoint: 0.012,
        trigger: 0,
        build_Speed: 0.015,
        position: 8,
        kingWarScore: 0.012,
        GetElitePoint: 1.2,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 1710007611,
            armyId: 612,
            armyName: "soldier_name_07",
            armyPic: "armyicon_b_1710007611.png",
            armySmallPic: "armyicon_s_1710007611.png",
            skill: [
                10231309,
                10231305,
                11501327
            ],
            modelType: 3,
            armyDes: "armyDes_10007611",
            tip: "armtip_32",
            starchange: 0
        }
    },
    armyC_13: {
        index: 1215,
        armyID: 5810009612,
        armyId: 513,
        armyType: 3,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 117,
        barrackLevel: 130,
        starchange: 0,
        starlv: 58,
        trainingTime: 330,
        costRes: {
            Grain: 1300,
            Lumber: 550,
            Iron: 90,
            Silver: 25,
            Crystal: 20
        },
        attack: 259,
        defense: 86,
        life: 638,
        atkInterval: 1,
        atkDistance: 5,
        speed: 8,
        strike: 50,
        freeWeight: 14,
        costFood: 0.63,
        power: 15,
        trainPoint: 0.015,
        trigger: 0,
        build_Speed: 0.017,
        position: 7,
        kingWarScore: 0.015,
        GetElitePoint: 1.5,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 5810009612,
            armyId: 513,
            armyName: "soldier_name_11",
            armyPic: "armyicon_b_5810009612.png",
            armySmallPic: "armyicon_s_5810009612.png",
            skill: [
                10241356,
                10241309,
                12501349
            ],
            modelType: 3,
            armyDes: "armyDes_10009612",
            tip: "armtip_31",
            starchange: 0
        }
    },
    armyC_14: {
        index: 1337,
        armyID: 7010009613,
        armyId: 514,
        armyType: 3,
        armorType: 1,
        battleUnitType: 0,
        barrackID: 117,
        barrackLevel: 130,
        starchange: 0,
        starlv: 70,
        trainingTime: 350,
        costRes: {
            1620: 8,
            Grain: 1300,
            Lumber: 550,
            Iron: 90,
            Silver: 25,
            Crystal: 20
        },
        attack: 380,
        defense: 117,
        life: 1692,
        atkInterval: 1,
        atkDistance: 5,
        speed: 8,
        strike: 50,
        freeWeight: 15,
        costFood: 0.65,
        power: 22,
        trainPoint: 0.022,
        trigger: 0,
        build_Speed: 0.018,
        position: 7,
        kingWarScore: 0.02,
        GetElitePoint: 2.2,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 7010009613,
            armyId: 514,
            armyName: "soldier_name_15",
            armyPic: "armyicon_b_10009613.png",
            armySmallPic: "armyicon_s_10009613.png",
            skill: [
                10251360,
                10251361,
                10251362,
                10251366
            ],
            modelType: 3,
            armyDes: "armyDes_10009513",
            tip: "armtip_31",
            starchange: 0
        }
    }
};