module.exports = {
    armyE_1: {},
    armyE_2: {},
    armyE_3: {},
    armyE_4: {},
    armyE_5: {},
    armyE_6: {
        index: 56,
        armyID: 906,
        armyId: 906,
        armyType: 5,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 302,
        barrackLevel: 1,
        starchange: 0,
        starlv: 0,
        trainingTime: 120,
        costRes: {
            Grain: 300,
            Lumber: 300,
            Iron: 50,
            Silver: 25
        },
        attack: 90,
        defense: 36,
        life: 300,
        atkInterval: 1.3,
        atkDistance: 9,
        speed: 10,
        strike: 50,
        freeWeight: 15,
        costFood: 0.3,
        power: 5,
        trainPoint: 0.005,
        trigger: 0,
        build_Speed: 0.01,
        position: 4,
        kingWarScore: 0.007,
        GetElitePoint: 0,
        UseElitePoint: 10,
        ArmyData: {
            armyID: 906,
            armyId: 906,
            armyName: "armyName_906",
            armyPic: "armyicon_b_906.png",
            armySmallPic: "armyicon_s_906.png",
            skill: [
                1329,
                1330,
                1331
            ],
            modelType: 6,
            armyDes: "armyDes_906",
            tip: "armtip_43",
            starchange: 0
        }
    },
    armyE_7: {
        index: 57,
        armyID: 907,
        armyId: 907,
        armyType: 5,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 302,
        barrackLevel: 2,
        starchange: 0,
        starlv: 0,
        trainingTime: 150,
        costRes: {
            Grain: 550,
            Lumber: 550,
            Iron: 90,
            Silver: 40
        },
        attack: 111,
        defense: 44,
        life: 372,
        atkInterval: 1.3,
        atkDistance: 9,
        speed: 10,
        strike: 50,
        freeWeight: 15,
        costFood: 0.35,
        power: 6.2,
        trainPoint: 0.0062,
        trigger: 0,
        build_Speed: 0.011,
        position: 4,
        kingWarScore: 0.008,
        GetElitePoint: 0,
        UseElitePoint: 15,
        ArmyData: {
            armyID: 907,
            armyId: 907,
            armyName: "armyName_907",
            armyPic: "armyicon_b_907.png",
            armySmallPic: "armyicon_s_907.png",
            skill: [
                1329,
                1330,
                1331
            ],
            modelType: 6,
            armyDes: "armyDes_907",
            tip: "armtip_43",
            starchange: 0
        }
    },
    armyE_8: {
        index: 58,
        armyID: 908,
        armyId: 908,
        armyType: 5,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 302,
        barrackLevel: 3,
        starchange: 0,
        starlv: 0,
        trainingTime: 180,
        costRes: {
            Grain: 700,
            Lumber: 700,
            Iron: 110,
            Silver: 50
        },
        attack: 140,
        defense: 56,
        life: 468,
        atkInterval: 1.3,
        atkDistance: 9,
        speed: 10,
        strike: 50,
        freeWeight: 15,
        costFood: 0.4,
        power: 7.8,
        trainPoint: 0.0078,
        trigger: 0,
        build_Speed: 0.012,
        position: 4,
        kingWarScore: 0.009,
        GetElitePoint: 0,
        UseElitePoint: 20,
        ArmyData: {
            armyID: 908,
            armyId: 908,
            armyName: "armyName_908",
            armyPic: "armyicon_b_908.png",
            armySmallPic: "armyicon_s_908.png",
            skill: [
                1329,
                1330,
                1331
            ],
            modelType: 6,
            armyDes: "armyDes_908",
            tip: "armtip_43",
            starchange: 0
        }
    },
    armyE_9: {
        index: 59,
        armyID: 909,
        armyId: 909,
        armyType: 5,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 302,
        barrackLevel: 4,
        starchange: 0,
        starlv: 0,
        trainingTime: 215,
        costRes: {
            Grain: 870,
            Lumber: 870,
            Iron: 140,
            Silver: 70
        },
        attack: 174,
        defense: 69,
        life: 582,
        atkInterval: 1.3,
        atkDistance: 9,
        speed: 10,
        strike: 50,
        freeWeight: 15,
        costFood: 0.45,
        power: 9.7,
        trainPoint: 0.0097,
        trigger: 0,
        build_Speed: 0.013,
        position: 4,
        kingWarScore: 0.01,
        GetElitePoint: 0,
        UseElitePoint: 25,
        ArmyData: {
            armyID: 909,
            armyId: 909,
            armyName: "armyName_909",
            armyPic: "armyicon_b_909.png",
            armySmallPic: "armyicon_s_909.png",
            skill: [
                1329,
                1330,
                1331
            ],
            modelType: 6,
            armyDes: "armyDes_909",
            tip: "armtip_43",
            starchange: 0
        }
    },
    armyE_10: {
        index: 60,
        armyID: 910,
        armyId: 910,
        armyType: 5,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 302,
        barrackLevel: 5,
        starchange: 0,
        starlv: 0,
        trainingTime: 270,
        costRes: {
            Grain: 1080,
            Lumber: 1080,
            Iron: 180,
            Silver: 90
        },
        attack: 216,
        defense: 86,
        life: 720,
        atkInterval: 1.3,
        atkDistance: 9,
        speed: 10,
        strike: 50,
        freeWeight: 15,
        costFood: 0.5,
        power: 12,
        trainPoint: 0.012,
        trigger: 0,
        build_Speed: 0.014,
        position: 4,
        kingWarScore: 0.011,
        GetElitePoint: 0,
        UseElitePoint: 30,
        ArmyData: {
            armyID: 910,
            armyId: 910,
            armyName: "armyName_910",
            armyPic: "armyicon_b_910.png",
            armySmallPic: "armyicon_s_910.png",
            skill: [
                1329,
                1330,
                1331
            ],
            modelType: 6,
            armyDes: "armyDes_910",
            tip: "armtip_43",
            starchange: 0
        }
    },
    armyE_11: {
        index: 1269,
        armyID: 10009613,
        armyId: 911,
        armyType: 5,
        armorType: 1,
        battleUnitType: 0,
        barrackID: 117,
        barrackLevel: 130,
        starchange: 54,
        starlv: 0,
        trainingTime: 350,
        costRes: {
            1620: 8,
            Grain: 1300,
            Lumber: 550,
            Iron: 90,
            Silver: 25,
            Crystal: 20
        },
        attack: 380,
        defense: 117,
        life: 1692,
        atkInterval: 1,
        atkDistance: 5,
        speed: 8,
        strike: 50,
        freeWeight: 15,
        costFood: 0.65,
        power: 22,
        trainPoint: 0.022,
        trigger: 0,
        build_Speed: 0.018,
        position: 7,
        kingWarScore: 0.02,
        GetElitePoint: 2.2,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 10009613,
            armyId: 911,
            armyName: "soldier_name_15",
            armyPic: "armyicon_b_10009613.png",
            armySmallPic: "armyicon_s_10009613.png",
            skill: [
                10251360,
                10251361,
                10251362,
                10251366
            ],
            modelType: 3,
            armyDes: "armyDes_10009613",
            tip: "armtip_31",
            starchange: 0
        }
    }
};