module.exports = {
    armyD_1: {
        index: 31,
        armyID: 701,
        armyId: 701,
        armyType: 4,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 119,
        barrackLevel: 1,
        starchange: 0,
        starlv: 0,
        trainingTime: 19,
        costRes: {
            Grain: 35,
            Lumber: 25,
            Iron: 0,
            Silver: 0
        },
        attack: 25,
        defense: 3,
        life: 30,
        atkInterval: 2.86,
        atkDistance: 10,
        speed: 7,
        strike: 0,
        freeWeight: 16,
        costFood: 0.05,
        power: 1,
        trainPoint: 0.001,
        trigger: 0,
        build_Speed: 0.005,
        position: 9,
        kingWarScore: 0.002,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 701,
            armyId: 701,
            armyName: "armyName_701",
            armyPic: "armyicon_b_701.png",
            armySmallPic: "armyicon_s_701.png",
            skill: [
                1315,
                1316
            ],
            modelType: 4,
            armyDes: "",
            tip: "armtip_42",
            starchange: 0
        }
    },
    armyD_2: {
        index: 32,
        armyID: 702,
        armyId: 702,
        armyType: 4,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 119,
        barrackLevel: 4,
        starchange: 0,
        starlv: 0,
        trainingTime: 23,
        costRes: {
            Grain: 60,
            Lumber: 40,
            Iron: 0,
            Silver: 0
        },
        attack: 24,
        defense: 9,
        life: 94,
        atkInterval: 1.43,
        atkDistance: 1,
        speed: 7,
        strike: 50,
        freeWeight: 22,
        costFood: 0.1,
        power: 1.4,
        trainPoint: 0.0014,
        trigger: 0,
        build_Speed: 0.006,
        position: 2,
        kingWarScore: 0.003,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 702,
            armyId: 702,
            armyName: "armyName_702",
            armyPic: "armyicon_b_702.png",
            armySmallPic: "armyicon_s_702.png",
            skill: [
                1318,
                1319,
                1320
            ],
            modelType: 4,
            armyDes: "armyDes_702",
            tip: "armtip_41",
            starchange: 0
        }
    },
    armyD_3: {
        index: 33,
        armyID: 703,
        armyId: 703,
        armyType: 4,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 119,
        barrackLevel: 7,
        starchange: 0,
        starlv: 0,
        trainingTime: 30,
        costRes: {
            Grain: 90,
            Lumber: 60,
            Iron: 0,
            Silver: 0
        },
        attack: 47,
        defense: 5,
        life: 57,
        atkInterval: 2.86,
        atkDistance: 10,
        speed: 7,
        strike: 0,
        freeWeight: 17,
        costFood: 0.15,
        power: 1.9,
        trainPoint: 0.0019,
        trigger: 0,
        build_Speed: 0.007,
        position: 9,
        kingWarScore: 0.004,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 703,
            armyId: 703,
            armyName: "armyName_703",
            armyPic: "armyicon_b_703.png",
            armySmallPic: "armyicon_s_703.png",
            skill: [
                1315,
                1316
            ],
            modelType: 4,
            armyDes: "armyDes_703",
            tip: "armtip_42",
            starchange: 0
        }
    },
    armyD_4: {
        index: 34,
        armyID: 704,
        armyId: 704,
        armyType: 4,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 119,
        barrackLevel: 10,
        starchange: 0,
        starlv: 0,
        trainingTime: 42,
        costRes: {
            Grain: 120,
            Lumber: 72,
            Iron: 2,
            Silver: 0
        },
        attack: 42,
        defense: 16,
        life: 167,
        atkInterval: 1.43,
        atkDistance: 1,
        speed: 7,
        strike: 50,
        freeWeight: 24,
        costFood: 0.2,
        power: 2.5,
        trainPoint: 0.0025,
        trigger: 0,
        build_Speed: 0.008,
        position: 2,
        kingWarScore: 0.005,
        GetElitePoint: 0.25,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 704,
            armyId: 704,
            armyName: "armyName_704",
            armyPic: "armyicon_b_704.png",
            armySmallPic: "armyicon_s_704.png",
            skill: [
                1318,
                1319,
                1320
            ],
            modelType: 4,
            armyDes: "armyDes_704",
            tip: "armtip_41",
            starchange: 0
        }
    },
    armyD_5: {
        index: 35,
        armyID: 705,
        armyId: 705,
        armyType: 4,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 119,
        barrackLevel: 13,
        starchange: 0,
        starlv: 0,
        trainingTime: 61,
        costRes: {
            Grain: 170,
            Lumber: 102,
            Iron: 5,
            Silver: 0
        },
        attack: 80,
        defense: 9,
        life: 96,
        atkInterval: 2.86,
        atkDistance: 10,
        speed: 7,
        strike: 0,
        freeWeight: 18,
        costFood: 0.25,
        power: 3.2,
        trainPoint: 0.0032,
        trigger: 0,
        build_Speed: 0.009,
        position: 9,
        kingWarScore: 0.006,
        GetElitePoint: 0.32,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 705,
            armyId: 705,
            armyName: "armyName_705",
            armyPic: "armyicon_b_705.png",
            armySmallPic: "armyicon_s_705.png",
            skill: [
                1315,
                1316
            ],
            modelType: 4,
            armyDes: "armyDes_705",
            tip: "armtip_42",
            starchange: 0
        }
    },
    armyD_6: {
        index: 36,
        armyID: 706,
        armyId: 706,
        armyType: 4,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 119,
        barrackLevel: 16,
        starchange: 0,
        starlv: 0,
        trainingTime: 76,
        costRes: {
            Grain: 250,
            Lumber: 150,
            Iron: 8,
            Silver: 0
        },
        attack: 68,
        defense: 25,
        life: 268,
        atkInterval: 1.43,
        atkDistance: 1,
        speed: 7,
        strike: 50,
        freeWeight: 26,
        costFood: 0.3,
        power: 4,
        trainPoint: 0.004,
        trigger: 0,
        build_Speed: 0.01,
        position: 2,
        kingWarScore: 0.007,
        GetElitePoint: 0.4,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 706,
            armyId: 706,
            armyName: "armyName_706",
            armyPic: "armyicon_b_706.png",
            armySmallPic: "armyicon_s_706.png",
            skill: [
                1318,
                1319,
                1320
            ],
            modelType: 4,
            armyDes: "armyDes_706",
            tip: "armtip_41",
            starchange: 0
        }
    },
    armyD_7: {
        index: 37,
        armyID: 707,
        armyId: 707,
        armyType: 4,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 119,
        barrackLevel: 19,
        starchange: 0,
        starlv: 0,
        trainingTime: 95,
        costRes: {
            Grain: 310,
            Lumber: 186,
            Iron: 11,
            Silver: 4
        },
        attack: 122,
        defense: 14,
        life: 147,
        atkInterval: 2.86,
        atkDistance: 10,
        speed: 7,
        strike: 0,
        freeWeight: 19,
        costFood: 0.35,
        power: 4.9,
        trainPoint: 0.0049,
        trigger: 0,
        build_Speed: 0.011,
        position: 9,
        kingWarScore: 0.008,
        GetElitePoint: 0.49,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 707,
            armyId: 707,
            armyName: "armyName_707",
            armyPic: "armyicon_b_707.png",
            armySmallPic: "armyicon_s_707.png",
            skill: [
                1315,
                1316
            ],
            modelType: 4,
            armyDes: "armyDes_707",
            tip: "armtip_42",
            starchange: 0
        }
    },
    armyD_8: {
        index: 38,
        armyID: 708,
        armyId: 708,
        armyType: 4,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 119,
        barrackLevel: 22,
        starchange: 0,
        starlv: 0,
        trainingTime: 114,
        costRes: {
            Grain: 420,
            Lumber: 252,
            Iron: 14,
            Silver: 6
        },
        attack: 147,
        defense: 17,
        life: 177,
        atkInterval: 2.86,
        atkDistance: 10,
        speed: 7,
        strike: 0,
        freeWeight: 20,
        costFood: 0.4,
        power: 5.9,
        trainPoint: 0.0059,
        trigger: 0,
        build_Speed: 0.012,
        position: 9,
        kingWarScore: 0.009,
        GetElitePoint: 0.59,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 708,
            armyId: 708,
            armyName: "armyName_708",
            armyPic: "armyicon_b_708.png",
            armySmallPic: "armyicon_s_708.png",
            skill: [
                1315,
                1316
            ],
            modelType: 4,
            armyDes: "armyDes_708",
            tip: "armtip_42",
            starchange: 0
        }
    },
    armyD_9: {
        index: 39,
        armyID: 709,
        armyId: 709,
        armyType: 4,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 119,
        barrackLevel: 26,
        starchange: 0,
        starlv: 0,
        trainingTime: 137,
        costRes: {
            Grain: 570,
            Lumber: 342,
            Iron: 17,
            Silver: 8
        },
        attack: 120,
        defense: 45,
        life: 470,
        atkInterval: 1.43,
        atkDistance: 1,
        speed: 7,
        strike: 50,
        freeWeight: 28,
        costFood: 0.45,
        power: 7,
        trainPoint: 0.007,
        trigger: 0,
        build_Speed: 0.013,
        position: 2,
        kingWarScore: 0.01,
        GetElitePoint: 0.7,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 709,
            armyId: 709,
            armyName: "armyName_709",
            armyPic: "armyicon_b_709.png",
            armySmallPic: "armyicon_s_709.png",
            skill: [
                1318,
                1319,
                1320
            ],
            modelType: 4,
            armyDes: "armyDes_709",
            tip: "armtip_41",
            starchange: 0
        }
    },
    armyD_10: {
        index: 40,
        armyID: 710,
        armyId: 710,
        armyType: 4,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 119,
        barrackLevel: 30,
        starchange: 0,
        starlv: 0,
        trainingTime: 171,
        costRes: {
            Grain: 780,
            Lumber: 468,
            Iron: 20,
            Silver: 10
        },
        attack: 205,
        defense: 24,
        life: 246,
        atkInterval: 2.86,
        atkDistance: 10,
        speed: 7,
        strike: 0,
        freeWeight: 21,
        costFood: 0.5,
        power: 8.2,
        trainPoint: 0.0082,
        trigger: 0,
        build_Speed: 0.014,
        position: 9,
        kingWarScore: 0.011,
        GetElitePoint: 0.82,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 710,
            armyId: 710,
            armyName: "armyName_710",
            armyPic: "armyicon_b_710.png",
            armySmallPic: "armyicon_s_710.png",
            skill: [
                1315,
                1316
            ],
            modelType: 4,
            armyDes: "armyDes_710",
            tip: "armtip_42",
            starchange: 0
        }
    },
    armyD_11: {
        index: 264,
        armyID: 10004711,
        armyId: 711,
        armyType: 4,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 119,
        barrackLevel: 80,
        starchange: 0,
        starlv: 0,
        trainingTime: 210,
        costRes: {
            Grain: 950,
            Lumber: 550,
            Iron: 50,
            Silver: 20,
            Crystal: 0
        },
        attack: 170,
        defense: 65,
        life: 700,
        atkInterval: 1.43,
        atkDistance: 1,
        speed: 7,
        strike: 50,
        freeWeight: 30,
        costFood: 0.55,
        power: 10.5,
        trainPoint: 0.0105,
        trigger: 0,
        build_Speed: 0.015,
        position: 2,
        kingWarScore: 0.012,
        GetElitePoint: 1.05,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 10004711,
            armyId: 711,
            armyName: "armyName_10004711",
            armyPic: "armyicon_b_10004711.png",
            armySmallPic: "armyicon_s_10004711.png",
            skill: [
                10211318,
                10211319,
                10211320,
                10241328
            ],
            modelType: 5,
            armyDes: "armyDes_10004711",
            tip: "armtip_41",
            starchange: 17
        }
    },
    armyD_12: {
        index: 552,
        armyID: 1710007711,
        armyId: 712,
        armyType: 4,
        armorType: 0,
        battleUnitType: 2,
        barrackID: 119,
        barrackLevel: 110,
        starchange: 0,
        starlv: 17,
        trainingTime: 210,
        costRes: {
            Grain: 950,
            Lumber: 550,
            Iron: 50,
            Silver: 20,
            Crystal: 0
        },
        attack: 224,
        defense: 76,
        life: 744,
        atkInterval: 1.43,
        atkDistance: 1,
        speed: 7,
        strike: 50,
        freeWeight: 32,
        costFood: 0.57,
        power: 12,
        trainPoint: 0.012,
        trigger: 0,
        build_Speed: 0.015,
        position: 2,
        kingWarScore: 0.012,
        GetElitePoint: 1.2,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 1710007711,
            armyId: 712,
            armyName: "soldier_name_08",
            armyPic: "armyicon_b_1710007711.png",
            armySmallPic: "armyicon_s_1710007711.png",
            skill: [
                10231320,
                10231316,
                10231318,
                1350
            ],
            modelType: 4,
            armyDes: "armyDes_10007711",
            tip: "armtip_41",
            starchange: 0
        }
    },
    armyD_13: {
        index: 1216,
        armyID: 5810009712,
        armyId: 713,
        armyType: 4,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 119,
        barrackLevel: 130,
        starchange: 0,
        starlv: 58,
        trainingTime: 285,
        costRes: {
            Grain: 1150,
            Lumber: 680,
            Iron: 75,
            Silver: 30,
            Crystal: 20
        },
        attack: 350,
        defense: 80,
        life: 545,
        atkInterval: 2.86,
        atkDistance: 10,
        speed: 7,
        strike: 0,
        freeWeight: 22,
        costFood: 0.63,
        power: 15,
        trainPoint: 0.015,
        trigger: 0,
        build_Speed: 0.017,
        position: 9,
        kingWarScore: 0.015,
        GetElitePoint: 1.5,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 5810009712,
            armyId: 713,
            armyName: "soldier_name_12",
            armyPic: "armyicon_b_5810009712.png",
            armySmallPic: "armyicon_s_5810009712.png",
            skill: [
                10241318,
                10241319,
                10241316,
                11501350
            ],
            modelType: 5,
            armyDes: "armyDes_10009712",
            tip: "armtip_42",
            starchange: 0
        }
    },
    armyD_14: {
        index: 1338,
        armyID: 7010009713,
        armyId: 714,
        armyType: 4,
        armorType: 1,
        battleUnitType: 0,
        barrackID: 119,
        barrackLevel: 130,
        starchange: 0,
        starlv: 70,
        trainingTime: 301,
        costRes: {
            1620: 8,
            Grain: 1150,
            Lumber: 680,
            Iron: 75,
            Silver: 30,
            Crystal: 20
        },
        attack: 475,
        defense: 143,
        life: 1520,
        atkInterval: 2.86,
        atkDistance: 10,
        speed: 7,
        strike: 0,
        freeWeight: 24,
        costFood: 0.65,
        power: 22,
        trainPoint: 0.022,
        trigger: 0,
        build_Speed: 0.018,
        position: 9,
        kingWarScore: 0.02,
        GetElitePoint: 2.2,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 7010009713,
            armyId: 714,
            armyName: "soldier_name_16",
            armyPic: "armyicon_b_10009713.png",
            armySmallPic: "armyicon_s_10009713.png",
            skill: [
                10251320,
                10251315,
                10251368
            ],
            modelType: 5,
            armyDes: "armyDes_10009613",
            tip: "armtip_42",
            starchange: 0
        }
    }
};