module.exports = {
    armyA_1: {
        index: 1,
        armyID: 401,
        armyId: 401,
        armyType: 1,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 118,
        barrackLevel: 1,
        starchange: 0,
        starlv: 0,
        trainingTime: 20,
        costRes: {
            Grain: 60,
            Lumber: 0,
            Iron: 0,
            Silver: 0
        },
        attack: 13,
        defense: 9,
        life: 75,
        atkInterval: 1.33,
        atkDistance: 1,
        speed: 8,
        strike: 50,
        freeWeight: 8,
        costFood: 0.05,
        power: 1,
        trainPoint: 0.001,
        trigger: 0,
        build_Speed: 0.005,
        position: 1,
        kingWarScore: 0.002,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 401,
            armyId: 401,
            armyName: "armyName_401",
            armyPic: "armyicon_b_401.png",
            armySmallPic: "armyicon_s_401.png",
            skill: [
                1301,
                1302,
                1303
            ],
            modelType: 1,
            armyDes: "",
            tip: "armtip_11",
            starchange: 0
        }
    },
    armyA_2: {
        index: 2,
        armyID: 402,
        armyId: 402,
        armyType: 1,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 118,
        barrackLevel: 4,
        starchange: 0,
        starlv: 0,
        trainingTime: 25,
        costRes: {
            Grain: 100,
            Lumber: 0,
            Iron: 0,
            Silver: 0
        },
        attack: 18,
        defense: 12,
        life: 105,
        atkInterval: 1.33,
        atkDistance: 1,
        speed: 8,
        strike: 50,
        freeWeight: 8,
        costFood: 0.1,
        power: 1.4,
        trainPoint: 0.0014,
        trigger: 0,
        build_Speed: 0.006,
        position: 1,
        kingWarScore: 0.003,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 402,
            armyId: 402,
            armyName: "armyName_402",
            armyPic: "armyicon_b_402.png",
            armySmallPic: "armyicon_s_402.png",
            skill: [
                1301,
                1302,
                1303
            ],
            modelType: 1,
            armyDes: "armyDes_402",
            tip: "armtip_11",
            starchange: 0
        }
    },
    armyA_3: {
        index: 3,
        armyID: 403,
        armyId: 403,
        armyType: 2,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 118,
        barrackLevel: 7,
        starchange: 0,
        starlv: 0,
        trainingTime: 32,
        costRes: {
            Grain: 120,
            Lumber: 30,
            Iron: 0,
            Silver: 0
        },
        attack: 28,
        defense: 15,
        life: 114,
        atkInterval: 1.07,
        atkDistance: 1,
        speed: 9,
        strike: 150,
        freeWeight: 9,
        costFood: 0.15,
        power: 1.9,
        trainPoint: 0.0019,
        trigger: 0,
        build_Speed: 0.007,
        position: 3,
        kingWarScore: 0.004,
        GetElitePoint: 0,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 403,
            armyId: 403,
            armyName: "armyName_403",
            armyPic: "armyicon_b_403.png",
            armySmallPic: "armyicon_s_403.png",
            skill: [
                1304,
                1305,
                1306
            ],
            modelType: 1,
            armyDes: "armyDes_403",
            tip: "armtip_12",
            starchange: 0
        }
    },
    armyA_4: {
        index: 4,
        armyID: 404,
        armyId: 404,
        armyType: 1,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 118,
        barrackLevel: 10,
        starchange: 0,
        starlv: 0,
        trainingTime: 45,
        costRes: {
            Grain: 170,
            Lumber: 0,
            Iron: 5,
            Silver: 0
        },
        attack: 32,
        defense: 22,
        life: 187,
        atkInterval: 1.33,
        atkDistance: 1,
        speed: 8,
        strike: 50,
        freeWeight: 9,
        costFood: 0.2,
        power: 2.5,
        trainPoint: 0.0025,
        trigger: 0,
        build_Speed: 0.008,
        position: 1,
        kingWarScore: 0.005,
        GetElitePoint: 0.25,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 404,
            armyId: 404,
            armyName: "armyName_404",
            armyPic: "armyicon_b_404.png",
            armySmallPic: "armyicon_s_404.png",
            skill: [
                1301,
                1302,
                1303
            ],
            modelType: 1,
            armyDes: "armyDes_404",
            tip: "armtip_11",
            starchange: 0
        }
    },
    armyA_5: {
        index: 5,
        armyID: 405,
        armyId: 405,
        armyType: 2,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 118,
        barrackLevel: 13,
        starchange: 0,
        starlv: 0,
        trainingTime: 65,
        costRes: {
            Grain: 170,
            Lumber: 70,
            Iron: 10,
            Silver: 0
        },
        attack: 47,
        defense: 25,
        life: 192,
        atkInterval: 1.07,
        atkDistance: 1,
        speed: 9,
        strike: 150,
        freeWeight: 10,
        costFood: 0.25,
        power: 3.2,
        trainPoint: 0.0032,
        trigger: 0,
        build_Speed: 0.009,
        position: 3,
        kingWarScore: 0.006,
        GetElitePoint: 0.32,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 405,
            armyId: 405,
            armyName: "armyName_405",
            armyPic: "armyicon_b_405.png",
            armySmallPic: "armyicon_s_405.png",
            skill: [
                1304,
                1305,
                1306
            ],
            modelType: 1,
            armyDes: "armyDes_405",
            tip: "armtip_12",
            starchange: 0
        }
    },
    armyA_6: {
        index: 6,
        armyID: 406,
        armyId: 406,
        armyType: 1,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 118,
        barrackLevel: 16,
        starchange: 0,
        starlv: 0,
        trainingTime: 80,
        costRes: {
            Grain: 330,
            Lumber: 0,
            Iron: 20,
            Silver: 0
        },
        attack: 52,
        defense: 36,
        life: 300,
        atkInterval: 1.33,
        atkDistance: 1,
        speed: 8,
        strike: 50,
        freeWeight: 10,
        costFood: 0.3,
        power: 4,
        trainPoint: 0.004,
        trigger: 0,
        build_Speed: 0.01,
        position: 1,
        kingWarScore: 0.007,
        GetElitePoint: 0.4,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 406,
            armyId: 406,
            armyName: "armyName_406",
            armyPic: "armyicon_b_406.png",
            armySmallPic: "armyicon_s_406.png",
            skill: [
                1301,
                1302,
                1303
            ],
            modelType: 1,
            armyDes: "armyDes_406",
            tip: "armtip_11",
            starchange: 0
        }
    },
    armyA_7: {
        index: 7,
        armyID: 407,
        armyId: 407,
        armyType: 1,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 118,
        barrackLevel: 19,
        starchange: 0,
        starlv: 0,
        trainingTime: 100,
        costRes: {
            Grain: 400,
            Lumber: 0,
            Iron: 30,
            Silver: 3
        },
        attack: 65,
        defense: 45,
        life: 329,
        atkInterval: 1.33,
        atkDistance: 1,
        speed: 8,
        strike: 50,
        freeWeight: 11,
        costFood: 0.35,
        power: 4.9,
        trainPoint: 0.0049,
        trigger: 0,
        build_Speed: 0.011,
        position: 1,
        kingWarScore: 0.008,
        GetElitePoint: 0.49,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 407,
            armyId: 407,
            armyName: "armyName_407",
            armyPic: "armyicon_b_407.png",
            armySmallPic: "armyicon_s_407.png",
            skill: [
                1301,
                1302,
                1303
            ],
            modelType: 1,
            armyDes: "armyDes_407",
            tip: "armtip_11",
            starchange: 0
        }
    },
    armyA_8: {
        index: 8,
        armyID: 408,
        armyId: 408,
        armyType: 2,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 118,
        barrackLevel: 22,
        starchange: 0,
        starlv: 0,
        trainingTime: 120,
        costRes: {
            Grain: 440,
            Lumber: 100,
            Iron: 40,
            Silver: 5
        },
        attack: 75,
        defense: 50,
        life: 354,
        atkInterval: 1.07,
        atkDistance: 1,
        speed: 9,
        strike: 150,
        freeWeight: 11,
        costFood: 0.4,
        power: 5.9,
        trainPoint: 0.0059,
        trigger: 0,
        build_Speed: 0.012,
        position: 3,
        kingWarScore: 0.009,
        GetElitePoint: 0.59,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 408,
            armyId: 408,
            armyName: "armyName_408",
            armyPic: "armyicon_b_408.png",
            armySmallPic: "armyicon_s_408.png",
            skill: [
                1304,
                1305,
                1306
            ],
            modelType: 1,
            armyDes: "armyDes_408",
            tip: "armtip_12",
            starchange: 0
        }
    },
    armyA_9: {
        index: 9,
        armyID: 409,
        armyId: 409,
        armyType: 2,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 118,
        barrackLevel: 26,
        starchange: 0,
        starlv: 0,
        trainingTime: 145,
        costRes: {
            Grain: 510,
            Lumber: 200,
            Iron: 50,
            Silver: 8
        },
        attack: 78,
        defense: 53,
        life: 385,
        atkInterval: 1.07,
        atkDistance: 1,
        speed: 9,
        strike: 150,
        freeWeight: 12,
        costFood: 0.45,
        power: 7,
        trainPoint: 0.007,
        trigger: 0,
        build_Speed: 0.013,
        position: 3,
        kingWarScore: 0.01,
        GetElitePoint: 0.7,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 409,
            armyId: 409,
            armyName: "armyName_409",
            armyPic: "armyicon_b_409.png",
            armySmallPic: "armyicon_s_409.png",
            skill: [
                1304,
                1305,
                1306
            ],
            modelType: 1,
            armyDes: "armyDes_409",
            tip: "armtip_12",
            starchange: 0
        }
    },
    armyA_10: {
        index: 10,
        armyID: 410,
        armyId: 410,
        armyType: 1,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 118,
        barrackLevel: 30,
        starchange: 0,
        starlv: 0,
        trainingTime: 180,
        costRes: {
            Grain: 640,
            Lumber: 300,
            Iron: 70,
            Silver: 10
        },
        attack: 106,
        defense: 73,
        life: 615,
        atkInterval: 1.33,
        atkDistance: 1,
        speed: 8,
        strike: 50,
        freeWeight: 12,
        costFood: 0.5,
        power: 8.2,
        trainPoint: 0.0082,
        trigger: 0,
        build_Speed: 0.014,
        position: 1,
        kingWarScore: 0.011,
        GetElitePoint: 0.82,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 410,
            armyId: 410,
            armyName: "armyName_410",
            armyPic: "armyicon_b_410.png",
            armySmallPic: "armyicon_s_410.png",
            skill: [
                1301,
                1302,
                1303
            ],
            modelType: 1,
            armyDes: "armyDes_410",
            tip: "armtip_11",
            starchange: 0
        }
    },
    armyA_11: {
        index: 231,
        armyID: 10004411,
        armyId: 411,
        armyType: 2,
        armorType: 0,
        battleUnitType: 0,
        barrackID: 118,
        barrackLevel: 80,
        starchange: 0,
        starlv: 0,
        trainingTime: 220,
        costRes: {
            Grain: 800,
            Lumber: 400,
            Iron: 100,
            Silver: 20,
            Crystal: 0
        },
        attack: 145,
        defense: 80,
        life: 650,
        atkInterval: 1.07,
        atkDistance: 1,
        speed: 9,
        strike: 150,
        freeWeight: 13,
        costFood: 0.55,
        power: 10.5,
        trainPoint: 0.0105,
        trigger: 0,
        build_Speed: 0.015,
        position: 3,
        kingWarScore: 0.012,
        GetElitePoint: 1.05,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 10004411,
            armyId: 411,
            armyName: "armyName_10004411",
            armyPic: "armyicon_b_10004411.png",
            armySmallPic: "armyicon_s_10004411.png",
            skill: [
                10211304,
                10211305,
                10211306,
                10241325
            ],
            modelType: 1,
            armyDes: "armyDes_10004411",
            tip: "armtip_12",
            starchange: 17
        }
    },
    armyA_12: {
        index: 549,
        armyID: 1710007411,
        armyId: 412,
        armyType: 2,
        armorType: 0,
        battleUnitType: 3,
        barrackID: 118,
        barrackLevel: 110,
        starchange: 0,
        starlv: 17,
        trainingTime: 220,
        costRes: {
            Grain: 800,
            Lumber: 400,
            Iron: 100,
            Silver: 20,
            Crystal: 0
        },
        attack: 150,
        defense: 85,
        life: 654,
        atkInterval: 1.07,
        atkDistance: 1,
        speed: 9,
        strike: 150,
        freeWeight: 13,
        costFood: 0.57,
        power: 12,
        trainPoint: 0.012,
        trigger: 0,
        build_Speed: 0.015,
        position: 3,
        kingWarScore: 0.012,
        GetElitePoint: 1.2,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 1710007411,
            armyId: 412,
            armyName: "soldier_name_05",
            armyPic: "armyicon_b_1710007411.png",
            armySmallPic: "armyicon_s_1710007411.png",
            skill: [
                10231304,
                10231305,
                10231306,
                12501325
            ],
            modelType: 1,
            armyDes: "armyDes_10007411",
            tip: "armtip_12",
            starchange: 0
        }
    },
    armyA_13: {},
    armyA_14: {
        index: 1335,
        armyID: 7010009413,
        armyId: 414,
        armyType: 1,
        armorType: 1,
        battleUnitType: 0,
        barrackID: 118,
        barrackLevel: 130,
        starchange: 0,
        starlv: 70,
        trainingTime: 316,
        costRes: {
            1620: 8,
            Grain: 1000,
            Lumber: 500,
            Iron: 130,
            Silver: 30,
            Crystal: 20
        },
        attack: 360,
        defense: 144,
        life: 1758,
        atkInterval: 1.07,
        atkDistance: 1,
        speed: 8,
        strike: 50,
        freeWeight: 17,
        costFood: 0.65,
        power: 22,
        trainPoint: 0.022,
        trigger: 0,
        build_Speed: 0.018,
        position: 1,
        kingWarScore: 0.02,
        GetElitePoint: 2.2,
        UseElitePoint: 0,
        ArmyData: {
            armyID: 7010009413,
            armyId: 414,
            armyName: "soldier_name_13",
            armyPic: "armyicon_b_10009413.png",
            armySmallPic: "armyicon_s_10009413.png",
            skill: [
                10251357,
                10251358,
                10251359,
                10251365
            ],
            modelType: 1,
            armyDes: "armyDes_10009613",
            tip: "armtip_11",
            starchange: 0
        }
    }
}