import internal from "stream";
import { EBuildingType } from "../Building.Const";

export interface IBuildingInfoUnit{
    index: number;
    idBuilding :number;
    buildingType :EBuildingType;
    bType: number;
    maxCount: number;
    isDemolish:boolean;
    isExchange:boolean;
    isBuild:boolean;
    isUpgrade:boolean;
    maxLvl: number;
    initLvl: number
    openWl: number;
    openStar: number;
    maxStarLvl: number;
}

export interface IBuildingInfo {
  [p: number]: IBuildingInfoUnit;
}
export const  BuildingInfo :IBuildingInfo  = {

  [EBuildingType.CBType_None] :{
    index: 0,
    idBuilding :0,
    buildingType :EBuildingType.CBType_None,
    bType: 0,
    maxCount: 0,
    isDemolish:false,
    isExchange:false,
    isBuild: false,
    isUpgrade:false,
    maxLvl: 0,
    initLvl: 0,
    openWl: 0,
    openStar: 0,
    maxStarLvl: 0
  },
  [EBuildingType.CBType_Castle] :{
    index: 1,
    idBuilding :101,
    buildingType :EBuildingType.CBType_Castle,
    bType: 0,
    maxCount: 1,
    isDemolish:false,
    isExchange:false,
    isBuild: false,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 1,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },
  [EBuildingType.CBType_Wall] :{
    index: 2,
    idBuilding : EBuildingType.CBType_Wall,
    buildingType : EBuildingType.CBType_Wall,
    bType: 0,
    maxCount: 1,
    isDemolish:false,
    isExchange:false,
    isBuild: false,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 1,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },
  [EBuildingType.CBType_ArrowTower] :{
    index: 3,
    idBuilding : EBuildingType.CBType_ArrowTower,
    buildingType : EBuildingType.CBType_ArrowTower,
    bType: 0,
    maxCount: 2,
    isDemolish:false,
    isExchange:false,
    isBuild: false,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 1,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },
  [EBuildingType.CBType_WatchTower] :{
    index: 4,
    idBuilding : EBuildingType.CBType_WatchTower,
    buildingType : EBuildingType.CBType_WatchTower,
    bType: 0,
    maxCount: 1,
    isDemolish:false,
    isExchange:false,
    isBuild: false,
    isUpgrade:true,
    maxLvl: 30,
    initLvl: 1,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },
  [EBuildingType.CBType_Warehouse] :{
    index: 5,
    idBuilding : EBuildingType.CBType_Warehouse,
    buildingType : EBuildingType.CBType_Warehouse,
    bType: 0,
    maxCount: 1,
    isDemolish:false,
    isExchange:true,
    isBuild: false,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 1,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },
  [EBuildingType.CBType_EventCenter] :{
    index: 6,
    idBuilding : EBuildingType.CBType_EventCenter,
    buildingType : EBuildingType.CBType_EventCenter,
    bType: 0,
    maxCount: 1,
    isDemolish:false,
    isExchange:true,
    isBuild: false,
    isUpgrade:false,
    maxLvl: 1,
    initLvl: 1,
    openWl: 1,
    openStar: 0,
    maxStarLvl: 0
  },
  [EBuildingType.CBType_Merchant] :{
    index: 7,
    idBuilding : EBuildingType.CBType_Merchant,
    buildingType : EBuildingType.CBType_Merchant,
    bType: 0,
    maxCount: 1,
    isDemolish:false,
    isExchange:false,
    isBuild: false,
    isUpgrade:false,
    maxLvl: 1,
    initLvl: 1,
    openWl: 1,
    openStar: 0,
    maxStarLvl: 0
  },
  [EBuildingType.CBType_Port] :{
    index: 8,
    idBuilding : EBuildingType.CBType_Port,
    buildingType : EBuildingType.CBType_Port,
    bType: 0,
    maxCount: 1,
    isDemolish:false,
    isExchange:false,
    isBuild: false,
    isUpgrade:false,
    maxLvl: 1,
    initLvl: 1,
    openWl: 1,
    openStar: 0,
    maxStarLvl: 0
  },
  [EBuildingType.CBType_TroopDetails] :{
    index: 9,
    idBuilding : EBuildingType.CBType_TroopDetails,
    buildingType : EBuildingType.CBType_TroopDetails,
    bType: 0,
    maxCount: 1,
    isDemolish:false,
    isExchange:false,
    isBuild: false,
    isUpgrade:false,
    maxLvl: 1,
    initLvl: 1,
    openWl: 1,
    openStar: 0,
    maxStarLvl: 0
  },
  [EBuildingType.CBType_Bulletin] :{
    index: 10,
    idBuilding : EBuildingType.CBType_Bulletin,
    buildingType : EBuildingType.CBType_Bulletin,
    bType: 0,
    maxCount: 1,
    isDemolish:false,
    isExchange:false,
    isBuild: false,
    isUpgrade:false,
    maxLvl: 1,
    initLvl: 1,
    openWl: 1,
    openStar: 0,
    maxStarLvl: 0
  },
  [EBuildingType.CBType_Embassy] :{
    index: 11,
    idBuilding : EBuildingType.CBType_Embassy,
    buildingType : EBuildingType.CBType_Embassy,
    bType: 0,
    maxCount: 1,
    isDemolish:false,
    isExchange: true,
    isBuild: true,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 1,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },
  [EBuildingType.CBType_Market] :{
    index: 12,
    idBuilding : EBuildingType.CBType_Market,
    buildingType : EBuildingType.CBType_Market,
    bType: 0,
    maxCount: 1,
    isDemolish:false,
    isExchange: true,
    isBuild: true,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 1,
    openWl: 0,
    openStar: 0,
    maxStarLvl: 0
  },
  [EBuildingType.CBType_Institute] :{
    index: 13,
    idBuilding : EBuildingType.CBType_Institute,
    buildingType : EBuildingType.CBType_Institute,
    bType: 0,
    maxCount: 1,
    isDemolish:false,
    isExchange: true,
    isBuild: true,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 1,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },
  [EBuildingType.CBType_TreasurePool] :{
    index: 14,
    idBuilding : EBuildingType.CBType_TreasurePool,
    buildingType : EBuildingType.CBType_TreasurePool,
    bType: 0,
    maxCount: 1,
    isDemolish:false,
    isExchange: true,
    isBuild: true,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 1,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },
  [EBuildingType.CBType_Blacksmith] :{
    index: 15,
    idBuilding : EBuildingType.CBType_Blacksmith,
    buildingType : EBuildingType.CBType_Blacksmith,
    bType: 0,
    maxCount: 1,
    isDemolish:false,
    isExchange: false,
    isBuild: false,
    isUpgrade:true,
    maxLvl: 30,
    initLvl: 1,
    openWl: 0,
    openStar: 0,
    maxStarLvl: 0
  },
  [EBuildingType.CBType_Stable] :{
    index: 16,
    idBuilding : EBuildingType.CBType_Stable,
    buildingType : EBuildingType.CBType_Stable,
    bType: 0,
    maxCount: 1,
    isDemolish:false,
    isExchange: true,
    isBuild: true,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 1,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },
  [EBuildingType.CBType_TargetRange] :{
    index: 17,
    idBuilding : EBuildingType.CBType_TargetRange,
    buildingType : EBuildingType.CBType_TargetRange,
    bType: 0,
    maxCount: 1,
    isDemolish:false,
    isExchange: true,
    isBuild: true,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 1,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },
  [EBuildingType.CBType_Barrack] :{
    index: 18,
    idBuilding : EBuildingType.CBType_Barrack,
    buildingType : EBuildingType.CBType_Barrack,
    bType: 0,
    maxCount: 1,
    isDemolish:false,
    isExchange: true,
    isBuild: true,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 1,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },
  [EBuildingType.CBType_Workshop] :{
    index: 19,
    idBuilding : EBuildingType.CBType_Workshop,
    buildingType : EBuildingType.CBType_Workshop,
    bType: 0,
    maxCount: 1,
    isDemolish:false,
    isExchange: true,
    isBuild: true,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 1,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },
  [EBuildingType.CBType_Fortress] :{
    index: 20,
    idBuilding : EBuildingType.CBType_Fortress,
    buildingType : EBuildingType.CBType_Fortress,
    bType: 0,
    maxCount: 1,
    isDemolish:false,
    isExchange: true,
    isBuild: true,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 1,
    openWl: 0,
    openStar: 0,
    maxStarLvl: 0
  },
  [EBuildingType.CBType_DrillGrounds] :{
    index: 21,
    idBuilding : EBuildingType.CBType_DrillGrounds,
    buildingType : EBuildingType.CBType_DrillGrounds,
    bType: 0,
    maxCount: 1,
    isDemolish:false,
    isExchange: true,
    isBuild: true,
    isUpgrade:true,
    maxLvl: 30,
    initLvl: 1,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },
  [EBuildingType.CBType_HallOfWar] :{
    index: 22,
    idBuilding : EBuildingType.CBType_HallOfWar,
    buildingType : EBuildingType.CBType_HallOfWar,
    bType: 0,
    maxCount: 1,
    isDemolish:false,
    isExchange: true,
    isBuild: true,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 1,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },
  [EBuildingType.CBType_Farm] :{
    index: 23,
    idBuilding : EBuildingType.CBType_Farm,
    buildingType : EBuildingType.CBType_Farm,
    bType: 1,
    maxCount: 10,
    isDemolish:true,
    isExchange: true,
    isBuild: true,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 1,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },
  [EBuildingType.CBType_LumberMill] :{
    index: 24,
    idBuilding : EBuildingType.CBType_LumberMill,
    buildingType : EBuildingType.CBType_LumberMill,
    bType: 1,
    maxCount: 10,
    isDemolish:true,
    isExchange: true,
    isBuild: true,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 1,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },
  [EBuildingType.CBType_IronMine] :{
    index: 25,
    idBuilding : EBuildingType.CBType_IronMine,
    buildingType : EBuildingType.CBType_IronMine,
    bType: 1,
    maxCount: 8,
    isDemolish:true,
    isExchange: true,
    isBuild: true,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 1,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },  
  [EBuildingType.CBType_SilverMine] :{
    index: 26,
    idBuilding : EBuildingType.CBType_SilverMine,
    buildingType : EBuildingType.CBType_SilverMine,
    maxCount: 8,
    bType: 1,
    isDemolish:true,
    isExchange: true,
    isBuild: true,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 1,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },
  [EBuildingType.CBType_MarchingTent] :{
    index: 27,
    idBuilding : EBuildingType.CBType_MarchingTent,
    buildingType : EBuildingType.CBType_MarchingTent,
    bType: 1,
    maxCount: 8,
    isDemolish:true,
    isExchange: true,
    isBuild: true,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 1,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },
  [EBuildingType.CBType_FirstAidTent] :{
    index: 28,
    idBuilding : EBuildingType.CBType_FirstAidTent,
    buildingType : EBuildingType.CBType_FirstAidTent,
    bType: 1,
    maxCount: 8,
    isDemolish:true,
    isExchange: true,
    isBuild: true,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 1,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },
  [EBuildingType.CBType_Miracle] :{
    index: 29,
    idBuilding : EBuildingType.CBType_Miracle,
    buildingType : EBuildingType.CBType_Miracle,
    bType: 3,
    maxCount: 1,
    isDemolish: false,
    isExchange: false,
    isBuild: true,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 30,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },
  [EBuildingType.CBType_ElitePalace] :{
    index: 30,
    idBuilding : EBuildingType.CBType_ElitePalace,
    buildingType : EBuildingType.CBType_ElitePalace,
    bType: 3,
    maxCount: 1,
    isDemolish: false,
    isExchange: false,
    isBuild: false,
    isUpgrade:true,
    maxLvl: 5,
    initLvl: 1,
    openWl: 0,
    openStar: 0,
    maxStarLvl: 0
  },
  //CBType_HeroTrainGround = 123,
  [EBuildingType.CBType_CrystalMine] :{
    index: 31,
    idBuilding : EBuildingType.CBType_CrystalMine,
    buildingType : EBuildingType.CBType_CrystalMine,
    bType: 3,
    maxCount: 1,
    isDemolish: false,
    isExchange: false,
    isBuild: false,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 1,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },
  [EBuildingType.CBType_HeroTrainGround] :{
    index: 32,
    idBuilding : EBuildingType.CBType_HeroTrainGround,
    buildingType : EBuildingType.CBType_HeroTrainGround,
    bType: 0,
    maxCount: 1,
    isDemolish: false,
    isExchange: false,
    isBuild: false,
    isUpgrade:true,
    maxLvl: 30,
    initLvl: 1,
    openWl: 0,
    openStar: 0,
    maxStarLvl: 0
  },

  [EBuildingType.CBType_MaterialWorkShop] :{
    index: 33,
    idBuilding : EBuildingType.CBType_MaterialWorkShop,
    buildingType : EBuildingType.CBType_MaterialWorkShop,
    bType: 0,
    maxCount: 1,
    isDemolish: false,
    isExchange: false,
    isBuild: false,
    isUpgrade:false,
    maxLvl: 30,
    initLvl: 1,
    openWl: 0,
    openStar: 0,
    maxStarLvl: 0
  },


//   CBType_Monument = 303,

//   CBType_LeisureHouse = 30001,
//   CARGO_SHIP = 30002,
//   CBType_PetHouse = 30003,
//   CBType_ResurrectionHall = 30004,
//   CBType_ServiceCenter = 30005,
//   CBType_EpicBattle = 30006
  [EBuildingType.CBType_HeroPrison] :{
    index: 34,
    idBuilding : EBuildingType.CBType_HeroPrison,
    buildingType : EBuildingType.CBType_HeroPrison,
    bType: 0,
    maxCount: 1,
    isDemolish: false,
    isExchange: false,
    isBuild: false,
    isUpgrade:true,
    maxLvl: 130,
    initLvl: 1,
    openWl: 1,
    openStar: 1,
    maxStarLvl: 70
  },
  [EBuildingType.CBType_StarBraveStatue] :{
    index: 35,
    idBuilding : EBuildingType.CBType_StarBraveStatue,
    buildingType : EBuildingType.CBType_StarBraveStatue,
    bType: 0,
    maxCount: 1,
    isDemolish: false,
    isExchange: false,
    isBuild: false,
    isUpgrade:false,
    maxLvl: 130,
    initLvl: 1,
    openWl: 0,
    openStar: 1,
    maxStarLvl: 160
  }
};