#pragma once

enum class EWorldInstanceClass {
  None = 0,
  WorldMapBuilding,
  WorldMapBuildingLod2,
  WorldMapBuildingLod,
  WorldMapLegendLord,
  WorldMapRemains,
  WorldMapIconLodInstance,
  WorldMapRemainsWar,
  WorldMapCastle,
  WorldMapIconLodCastle,
  WorldMapBattery,
  WorldMapIconLodBattery,
  WorldMapFortress,
  WorldMapResource,
  WorldMapResourceLod2,
  WorldMapResourceLod,
  WorldMapCampsite,
  WorldMapIconLodCampsite,
  WorldMapMonster,
  WorldMapMonsterLod,
  WorldMapAllianceBuild,
  WorldMapAllianceBuildLod,
  WorldMapMonsterNebula,
  WorldMapMonsterSnowMan,
  WorldMapMonsterSemluk,
  WorldMapMonsterSea,
  WorldMapMonsterFiesta,
  WorldMapBoss,
  WorldMapBossWindTower,
  WorldMapIconLodBoss,
  WorldMapAllianceResource,
  WorldMapIconLodAlliance,
  WorldMapTreasure,
  WorldMapChest,
  WorldMapTreasureBowl,
  WorldMapBattlefieldSite,
  WorldMapEscort,
  WorldMapMineBuild,
  WorldMapIconLodMine,
  WorldMapStronghold,
  WorldMapIconLodStrong,
  WorldMapKingdomLvTower,
  WorldMapPyramidGloryBuild,
  WorldMapNewTrialCity,
  WorldMapTrialBattery,
  WorldMapWrathBeast,
  WorldMapFeast,
  WorldMapProtal,
  WorldMapAncientTreasure,
  WorldMapRedTreasureMap,
  WorldMapDrumAndVuln,
  WorldMapRadianceWarResource,
  WorldMapRadianceWarPalace,
  WorldMapRadianceWarGate,
  WorldMapRadianceWarBeacon,
  WorldMapAnniversaryCamp,
  WorldMapLostRuins,
  WorldMapWindTower,
  WorldMapAtlantisWar,
  WorldMapAtlantisWarLod,
  WorldMapBossAtlantis,
  WorldMapBossAtlantisLod,
  WorldMapSnowWolfLost,
  WorldMapStarTreasure,
  WorldMapNebulaWar,
  WorldMapNebulaWarLod,
  WorldMapNebulaWarMine,
  WorldMapDesertMeteorite,
};


enum class EMapNpcFaceTypeDef {
  None = 0,
  LeftBottom = 1,
  RightBottom = 2
};

enum class ELodLayer {
  None = 0,
  NORMAL = 1,
  NPC = 2,
  ALLIANCE = 3,
  SELF = 4,
  CASTLE = 5,
  ALLIANCERES = 6,
  ALLIANCESTRONG = 7,
  MONSTER = 8,
  BOSS = 9,
  NEBULA = 10,
  NEBULA_4 = 11
};

enum class EMapObjStateTypeDef{
  None = 0,
  Free = 1,
  Fighting = 2,
  HurtDie = 3,
  Working = 4
};

enum class EMapAllianceBuildType{
  None = 0,
  Palace = 1,
  Fort = 2,
  WarHall = 3,
  Shelter = 4,
  KnowledgeTower = 5,
  Flag = 6,
  Altar = 8,
  PriPalace = 9
};

enum class ESignatureBoxType{
  None = 0,
  Normal = 1,
  War = 2
};

enum class ESkillEffectType {
  None = 0,
  RUINS_WAR_MOVE_CITY_LOCKED = 1,
  RUINS_WAR_SPEED_QUEUE_LOCKED = 2,
  APPOINT_DAMAGE_BOOST = 3,
  APPOINT_CURE_SOLDIER_SPEED_BOOST = 4
};


enum class EKWBattery{
  None = 0,
  NORTH = 11,
  EAST = 14,
  SOUTH = 13,
  WEST = 12
};


enum class EMapBattlefieldSiteTypeDef {
  None = 0,
  ObjTypeBigPyramid = 1,
  ObjTypeSmallPyramid = 2,
  ObjTypeSuplly = 3,
  ObjTypeTransport = 4,
  ObjTypeBlessTower = 5,
  ObjTypeMedicalCenter = 6,
  ObjTypeStage = 7,
  ObjTypeRelic = 8,
  ObjTypeBattery = 9,
  TypeAWBellTower = 10,
  TypeAWArmory = 11
};

enum class EMapNewTrialBuildType {
  Castle = 1, 
  Battery = 2
};

enum class EWorldTypeServerDef {
  mapObjPlayer = 21,
  mapObjResource = 22,
  mapObjNpc = 23,
  mapObjRelics = 24,
  mapSettingResource = 1,
  mapSettingNpc = 2,
  mapSettingRelics = 3,
  mapTypeNone = 0,
  mapTypePlain = 1,
  mapTypeRivers = 2,
  mapTypeStone = 3,
  mapTypePlayer = 4,
  mapTypeResource = 5,
  mapTypeNpc = 6,
  mapTypeRelics = 7,
  mapTypeCamp = 8,
  mapTypeCastle = 9,
  mapTypeBattery = 10,
  mapTypeRef = 11,
  mapTypeTreasure = 12,
  mapTypeChest = 13,
  mapTypeSuperResource = 14,
  mapTypeBoss = 15,
  mapTypeEscort = 16,
  mapTypeAllianceWarBuilding = 17,
  mapTypeKingWarBuilding = 18,
  mapTypeAllianceBuild = 19,
  mapTypeTreasureBowl = 20,
  mapTypeKingdomLevelBuild = 21,
  mapTypeLegendLordWarBuilding = 22,
  mapTypeHeroBattleBoss1 = 23,
  mapTypeHeroBattleBoss2 = 24,
  mapTypeRuinsWarBuilding = 25,
  mapTypeMonsterFiesta = 26,
  mapTypeDevilValleyWarBuilding = 27,
  mapTypeSeaMonsterInvade = 28,
  mapTypeWrathBeast = 29,
  mapTypeEndlessTrialsPortal = 30,
  mapTypeATBuilding = 31,
  mapTypeWerewolf = 32,
  mapTypeFireTreasure = 33,
  mapTypeWarTreasure = 34,
  mapTypeFortyThieves = 35,
  mapTypeRadianceWarPalace = 36,
  mapTypeRadianceWarGate = 37,
  mapTypeRadianceWarBeacon = 38,
  mapTypeRadianceWarResource = 39,
  mapTypeSemruk = 40,
  mapTypePyramidGloryBuild = 41,
  mapType20Campfire = 42,
  mapTypeLostRuins = 43,
  mapTypeHuntFair = 44,
  mapTypeIceSnowWonder = 45,
  mapTypeWindTower = 46,
  mapTypeSnowWolfLost = 47,
  desertMeteorite = 60,
  subMapTypeWarTreasureDrum = 1,
  subMapTypeWarTreasureMedicine = 2,
  subMapTypeResGold = 1,
  subMapTypeResFood = 2,
  subMapTypeResWood = 3,
  subMapTypeResIron = 4,
  subMapTypeResMithril = 5,
  subMapTypeResCrystal = 6,
  subMapTypeSuperResFood = 1,
  subMapTypeSuperResWood = 2,
  subMapTypeSuperResIron = 3,
  subMapTypeSuperResMithril = 4,
  subMapTypeSuperResCrystal = 5,
  subMapTypeAWGreatPyramid = 1,
  subMapTypeAWSmallPyramid = 2,
  subMapTypeAWSupplyPoint = 3,
  subMapTypeAWTransPoint = 4,
  subMapTypeAWBlessedTower = 5,
  subMapTypeAWMedicalHall = 6,
  subMapTypeAWStation = 7,
  subMapTypeAWRelic = 8,
  subMapTypeAWBattery = 9,
  subMapTypeKWFort = 3,
  subTypeAlliancePalace = 1,
  subTypeAllianceFort = 2,
  subTypeAllianceWarHall = 3,
  subTypeAllianceShelter = 4,
  subTypeAllianceKnowledgeTower = 5,
  subTypeAllianceFlag = 6,
  subTypeAllianceAltar = 8,
  subTypeAlliancePriPalace = 9,
  subMapTypeLLWMainStatue = 1,
  subMapTypeDVWCastle = 1,
  subMapTypeDVWBattery = 2,
  mapAllRefreshHour = 1,
  subMapTypeRadianceWarResMedalWorkshop = 1,
  subMapTypeRadianceWarResAdvMedalWorkshop = 2,
  subMapTypeRadianceWarResRadiantQuarry = 3,
  subMapTypeRadianceWarResAstralRuins = 4,
  subMapTypeRadianceWarResAmberMine = 5,
  subMapTypeRadianceWarResAstralMine = 6,
  mapTypeAtlantisWarBuilding = 48,
  subMapTypeAtlantisWarPalace = 1,
  subMapTypeAtlantisWarFort = 2,
  subMapTypeAtlantisWarBattery = 3,
  nebulaWarBuilding = 55,
  subTypeNebulaWarPalace = 1,
  subTypeNebulaWarFort = 2,
  subTypeNebulaWarCamp = 3,
  subTypeNebulaWarTower = 4,
  subTypeNebulaWarBuild5 = 5,
  subTypeNebulaWarBuild6 = 6
};