#pragma once


enum class EAttributeEnum {
  None = 0,
  BATTLE_ATTACK_RATE = 1,
  BATTLE_DEFEND_RATE = 2,
  BATTLE_HP_RATE = 3,
  REINFORCEMENT_CAPACITY_NUM = 4,
  DISPATCH_TROOP_COUNT_NUM = 5,
  GATHER_RESOURCE_SPEED_RATE = 6,
  WOUNDED_CAPACITY_NUM = 7,
  DISPATCH_SPEED_RATE = 8,
  BUILDING_TRAIN_SPEED_RATE = 9,
  ASSEMBLY_TROOP_COUNT_NUM = 10,
  RESEARCH_TECHNOLOGY_SPEED_RATE = 11,
  TROOP_LOAD_RATE = 12,
  BUILDING_TRAIN_NUM = 13,
  BATTLE_DAMAGE_RATE = 14,
  BUILD_RES_OUTPUT_RATE = 15,
  BUILD_SPEED_UP_RATE = 16,
  DAMAGE_REDUCE_RATE = 17,
  COMBO_RATE = 18,
  BATTLE_DAMAGE_FOR_TARGET_RATE = 19,
  CRIT_RATE = 20,
  CURE_SOLDIER_SPEED_BOOST = 21,
  MASS_SLAVE_SPEED_RATE = 22,
  OCCUPY_ADD_ALLIANCE_SCORE = 23,
  MASS_SLAVE_ATTACK_RATE = 24,
  BATTLE_ATTACK_RATE_RANGE = 25,
  BATTLE_DEFEND_RATE_RANGE = 26,
  PROMOTE_BUILD_OCCUPY_NUM = 27,
  ACTIVITY_EXCHANGE_LIMIT_UP = 28,
  ATTACK_INTERVAL_REDUCE = 29,
  WOUNDED_ARMY_REBACK = 30,
  DAMAGE_REDUCE_RATE_NEW = 32,
  BATTLE_HP_RATE_RANGE = 33,
  BATTLE_DAMAGE_RATE_RANGE = 34,
  MARCH_SPEED_BOOST_RAGNE = 35,
  CURE_SOLDIER_SPEED_BOOST_RANGE = 36,
  HALLOFWAR_ARMY_UP_RANGE = 37,
  MASS_SLAVE_PLUS = 38,
  HALLOFWAR_ARMY_UP_PERCENT = 39,
  METEOR_TROOP_ATTACK_BOOST = 40,
  METEOR_TROOP_DEFENSE_BOOST = 41,
  METEOR_MARCH_SPEED_BOOST = 42,
  METEOR_TROOP_HP_BOOST = 43
};

enum class EAttributeLifeEnum {
  NONE = 0,
  TIME = 1,
  COUNT = 2,
  TIME_AND_COUNT = 3,
  DAILY_RESET_COUNT = 4
};

enum class EAttrValueType {
  num = 1,
  percentage = 2
};

enum class EAttributeSourceEnum {
  DRESS = 1,
  WRATH_BEAST_ACTIVITY = 2,
  GOD_ARMS = 3,
  TALENT_SKILL = 4,
  EQUIPMENT = 5
};
